Repository terraform-redhat/terraform-provider-rhcs, pull requests merged in 2023-09, with the labels that each got.

#238 Allow using empty default value (null) for availability_zones
  provider/cluster_rosa_classic_resource.go
Labels: approved, lgtm

#258 OCM-2720: rosa_oidc_config tf resource: Recreate resource if it was deleted not from tf
  provider/rosa_oidc_config_resource.go
Labels: approved, jira/valid-reference, lgtm

#263 Fix bad text replacements
  build/ci-tf-e2e.Dockerfile
  build/info.go
  ci/apply_folder.sh
  ci/e2e/terraform_provider_ocm_fullcycle_test.go
  internal/rhcs/cloudprovider/cloud_providers_state.go
  internal/rhcs/cluster/clusterschema/cluster_schema.go
  internal/rhcs/idps/gitlab.go
  internal/rhcs/idps/identity_provider_resource.go
  internal/rhcs/idps/identity_provider_state.go
  internal/rhcs/machinetypes/machine_types_state.go
  internal/rhcs/provider/provider.go
  internal/rhcs/rolesandpolicies/rosa_operator_roles_data_source.go
  logging/logging.go
  main.go
  scripts/run_make_e2e_test.py
  subsystem/cluster_resource_rosa_test.go
  subsystem/group_membership_resource_test.go
  subsystem/identity_provider_resource_test.go
  subsystem/init_test.go
  subsystem/machine_pool_resource_test.go
  tests/README.md
  tests/utils/constants/constants.go
Labels: approved

#268 Move provider to new "provider" package
  oldprovider/cluster_resource.go
  oldprovider/cluster_resource_test.go
  oldprovider/cluster_state.go
  oldprovider/enum_value_validator.go
  oldprovider/group_membership_resource.go
  oldprovider/group_membership_state.go
  oldprovider/group_state.go
  oldprovider/groups_data_source.go
  oldprovider/groups_state.go
  oldprovider/identity_provider_resource.go
  oldprovider/identity_provider_state.go
  oldprovider/idps/github.go
  oldprovider/idps/gitlab.go
  oldprovider/idps/google.go
  oldprovider/idps/htpasswd.go
  oldprovider/idps/ldap.go
  oldprovider/idps/mapping_method_validator.go
  oldprovider/idps/openid.go
  oldprovider/machine_pool_resource.go
  oldprovider/machine_pool_state.go
  oldprovider/machine_type_state.go
  oldprovider/machine_types_data_source.go
  oldprovider/machine_types_state.go
  oldprovider/ocm_policies_data_source.go
  oldprovider/ocm_policies_state.go
  oldprovider/provider_suite_test.go
  oldprovider/rosa_oidc_config_input_resource.go
  oldprovider/rosa_oidc_config_input_state.go
  oldprovider/rosa_oidc_config_resource.go
  oldprovider/rosa_oidc_config_state.go
  oldprovider/rosa_operator_roles_data_source.go
  oldprovider/rosa_operator_roles_state.go
  oldprovider/sts.go
  oldprovider/upgrade/cluster_upgrade.go
  oldprovider/value_cannot_be_changed_modifier.go
  oldprovider/version_state.go
  oldprovider/versions_data_source.go
  oldprovider/versions_state.go
  provider/cloudprovider/cloud_provider_state.go
  provider/cloudprovider/cloud_providers_data_source.go
  provider/cloudprovider/cloud_providers_state.go
  provider/clusterrosaclassic/cluster_rosa_classic_resource.go
  provider/clusterrosaclassic/cluster_rosa_classic_resource_test.go
  provider/clusterrosaclassic/cluster_rosa_classic_state.go
  provider/clusterwaiter/cluster_waiter_resource.go
  provider/clusterwaiter/cluster_waiter_state.go
  provider/dnsdomain/dns_domain_resource.go
  provider/dnsdomain/dns_domain_state.go
  provider/provider.go
Labels: approved, lgtm

#271 Update the conversions to be updated with the new types
  provider/common/tfconversions.go
Labels: approved, lgtm

#272 Remove the schema import aliases and simplify to New()
  provider/cloudprovider/cloud_providers_data_source.go
  provider/clusterwaiter/cluster_waiter_resource.go
  provider/dnsdomain/dns_domain_resource.go
  provider/provider.go
Labels: approved, lgtm

#257 OCM-3005: Fix allow private cluster without private link
  internal/ocm/resource/cluster.go
  internal/ocm/resource/cluster_test.go
  subsystem/cluster_resource_rosa_test.go
Labels: approved, jira/valid-reference, lgtm

#266 SDKv2: Fixup of machine types data source
  internal/rhcs/machinetypes/machine_types_data_source.go
Labels: lgtm

#278 Fixing issue with missing http client
  provider/common/http_client.go
Labels: approved, lgtm

#281 OCM-3210: ocm_policies_data_source also expose shared vpc operator policy
  provider/ocm_policies_data_source.go
  provider/ocm_policies_state.go
Labels: approved, jira/valid-reference, lgtm

#279 Migrate versions_data_source
  oldprovider/versions_state.go
  provider/provider.go
  provider/versions/versions_data_source.go
  provider/versions/versions_state.go
Labels: approved, lgtm

#270 Framework: added common attr validators
  provider/common/attrvalidators/list.go
  provider/common/attrvalidators/object.go
  provider/common/attrvalidators/string.go
  provider/common/attrvalidators/string_enum.go
Labels: lgtm

#282 Migrate machine_types data source
  oldprovider/machine_type_state.go
  provider/machine_types/machine_types_data_source.go
  provider/machine_types/machine_types_state.go
  provider/provider.go
Labels: approved, lgtm

#283 Migrate rosa_operator_roles data source
  provider/provider.go
  provider/rosa_operator_roles/rosa_operator_roles_data_source.go
  provider/rosa_operator_roles/rosa_operator_roles_state.go
Labels: approved, lgtm

#285 Typo fix for VersionsDataSource object
  provider/versions/versions_data_source.go
Labels: approved, lgtm

#269 Cluster rosa
  .vscode/launch.json
  oldprovider/cluster_state.go
  oldprovider/enum_value_validator.go
  oldprovider/sts.go
  oldprovider/value_cannot_be_changed_modifier.go
  provider/clusterrosaclassic/cluster_rosa_classic_resource.go
  provider/clusterrosaclassic/cluster_rosa_classic_resource_test.go
  provider/clusterrosaclassic/cluster_rosa_classic_state.go
  provider/clusterrosaclassic/upgrade/cluster_upgrade.go
  provider/common/tfconversions.go
  provider/provider.go
  subsystem/cluster_resource_rosa_test.go
Labels: approved, lgtm

#289 OCM-3735: IDP's uses framework built-in validators
  provider/clusterrosaclassic/admin_creds_validator.go
  provider/clusterrosaclassic/cluster_rosa_classic_resource.go
  provider/common/helpers.go
  provider/identityprovider/github.go
  provider/identityprovider/gitlab.go
  provider/identityprovider/google.go
  provider/identityprovider/htpasswd.go
  provider/identityprovider/identity_provider_resource.go
  provider/identityprovider/ldap.go
  provider/identityprovider/mapping_method_validator.go
Labels: approved, jira/valid-reference, lgtm

#290 Availability zones should be computed field as there is default value in OCM
  provider/cluster/cluster_resource.go
  provider/clusterrosaclassic/cluster_rosa_classic_resource.go
  subsystem/cluster_resource_rosa_test.go
  subsystem/cluster_resource_test.go
Labels: approved, lgtm

#291 Fix machine pool validation
  provider/machinepool/machine_pool_resource.go
  subsystem/machine_pool_resource_test.go
Labels: approved, lgtm

#294 make build: Change Makefile to ignore prerelease suffix when choosing the version
  Makefile
Labels: approved, lgtm

#245 Create cluster by profile env - add parser from yaml to cluster obj
  go.mod
  go.sum
  tests/README.md
  tests/ci/config.go
  tests/ci/connection.go
  tests/ci/file.go
  tests/ci/profile_handler.go
  tests/ci/profiles/tf_cluster_profile.yml
  tests/e2e/cluster_creation.go
  tests/e2e/init_test.go
  tests/e2e/machine_pool_test.go
  tests/tf-manifests/aws/account-roles/main.tf
  tests/tf-manifests/aws/account-roles/output.tf
  tests/tf-manifests/aws/account-roles/variables.tf
  tests/tf-manifests/rhcs/clusters/rosa-classic/main.tf
  tests/utils/connection/accounts.go
  tests/utils/connection/token.go
  tests/utils/constants/constants.go
  tests/utils/exec/account-roles.go
  tests/utils/exec/cluster.go
  tests/utils/exec/machine-pools.go
  tests/utils/exec/tf-exec.go
  tests/utils/exec/vpc.go
  tests/utils/helper/helper.go
  tests/utils/helper/parse_yaml.go
  tests/utils/helper/versions.go
Labels: approved, lgtm

#296 Fixed broken subsystem tests due to base_dns_domain plan modifiers
  provider/clusterrosaclassic/cluster_rosa_classic_resource.go
  subsystem/cluster_resource_rosa_test.go
Labels: approved, lgtm

#301 removing the candidate channel group from the examples
  examples/create_rosa_sts_cluster/oidc_configuration/cluster_with_unmanaged_oidc_config/main.tf
Labels: approved, lgtm

#300 Fix for disabling autoscale
  provider/clusterrosaclassic/cluster_rosa_classic_resource.go
Labels: approved, lgtm

#295 remove css cluster example as not supported
  examples/create_ccs_cluster/README.md
  examples/create_ccs_cluster/main.tf
Labels: approved, lgtm

#302 OCM-3795: Adding http tokens default to terraform state
  provider/clusterrosaclassic/cluster_rosa_classic_resource.go
Labels: approved, jira/valid-reference, lgtm

#303 OCM-3795: Adding http tokens default to terraform state
  provider/cluster_rosa_classic_resource.go
Labels: approved, jira/valid-reference, lgtm

#304 OCM-3807: Fix import of LDAP IDP bug
  provider/identityprovider/identity_provider_resource.go
Labels: approved, jira/valid-reference, lgtm

#306 Fix isNull -> isUnknown in google idp
  provider/identityprovider/google.go
Labels: approved, lgtm

#310 OCM-3794: Cluster name length should be at most 15 characters
  provider/clusterrosaclassic/cluster_rosa_classic_resource.go
  subsystem/cluster_resource_rosa_test.go
Labels: approved, jira/valid-reference, lgtm

#309 Fix update proxy in cluster rosa
  provider/clusterrosaclassic/cluster_rosa_classic_resource.go
  provider/proxy/proxy_validator.go
  subsystem/cluster_resource_rosa_test.go
Labels: approved, lgtm

#311 Change "terraform-redhat/rosa-sts" version to 0.0.14
  ci/e2e/account_roles_files/main.tf
  ci/e2e/oidc_configuration/cluster_with_managed_oidc_config/main.tf
  ci/e2e/oidc_configuration/cluster_with_unmanaged_oidc_config/main.tf
  examples/create_account_roles/main.tf
  examples/create_rosa_sts_cluster/classic_sts/cluster/main.tf
  examples/create_rosa_sts_cluster/oidc_configuration/oidc_provider/main.tf
  tests/tf-manifests/aws/account-roles/main.tf
  tests/tf-manifests/rhcs/clusters/rosa-classic/main.tf
Labels: approved, lgtm

#312 OCM-3828: HTPasswd IDP unique username validation
  provider/common/attrvalidators/list.go
  provider/identityprovider/htpasswd.go
  subsystem/identity_provider_resource_test.go
Labels: approved, jira/valid-reference, lgtm

#318 Correct provider source on umanaged cluster example
  examples/create_rosa_sts_cluster/oidc_configuration/cluster_with_unmanaged_oidc_config/main.tf
Labels: approved, lgtm

#314 OCM-2712: Allow specifying pool subnet even for 1AZ clusters
  provider/machinepool/machine_pool_resource.go
  subsystem/machine_pool_resource_test.go
Labels: approved, jira/valid-reference, lgtm
