Repository terraform-redhat/terraform-provider-rhcs, pull requests merged in 2023-12, with the labels that each got.

#414 OCM-5094 | chore: add initial OCM engineers to owners file
  OWNERS
Labels: approved, lgtm, ok-to-test

#420 insecure-skip-tls-verify and timeout fix
  tests/e2e/verfication_post_day1_test.go
Labels: approved, lgtm

#421 Exclude @OCP-65928 from CI run
  tests/e2e/verfication_post_day1_test.go
Labels: approved, lgtm

#415 OCM-4621: Change proxy validator to support only `additional_trust_bu…
  provider/clusterrosaclassic/cluster_rosa_classic_resource.go
  provider/proxy/proxy_validator.go
  subsystem/cluster_resource_rosa_test.go
Labels: approved, jira/valid-reference, lgtm

#400 add dns-domain resource & rhcs-info tf data methods and tests
  tests/e2e/general_day_two_test.go
  tests/tf-manifests/rhcs/dns/main.tf
  tests/tf-manifests/rhcs/dns/output.tf
  tests/tf-manifests/rhcs/dns/variable.tf
  tests/tf-manifests/rhcs/rhcs-info/main.tf
  tests/tf-manifests/rhcs/rhcs-info/variable.tf
  tests/utils/cms/cms.go
  tests/utils/constants/constants.go
  tests/utils/exec/dns-domain.go
  tests/utils/exec/import.go
  tests/utils/exec/rhcs-info.go
  tests/utils/exec/tf-exec.go
  tests/utils/helper/helper.go
Labels: approved, lgtm

#427 OCM-4621: avoid adding proxy to builder in case all values are empty
  provider/clusterrosaclassic/cluster_rosa_classic_resource.go
Labels: approved, jira/valid-reference, lgtm

#428 OCM-4621: avoid adding proxy to builder in case all values are empty
  provider/clusterrosaclassic/cluster_rosa_classic_resource.go
Labels: approved, jira/valid-reference, lgtm

#405 Release v1.4.2
  CHANGELOG.md
Labels: approved, do-not-merge/hold, lgtm

#432 OCM-5015: Fix max_node_provision_time attribute usage in the example
  examples/create_cluster_autoscaler/main.tf
Labels: approved, jira/valid-reference, lgtm

#433 OCM-5233 | fix: remove compute SGs from state
  provider/cluster/cluster_resource.go
  provider/clusterrosaclassic/cluster_rosa_classic_resource.go
Labels: approved, lgtm

#434 V1.4.0 zone fix - remove hardcoded AZones
  tests/ci/profiles/tf_cluster_profile.yml
Labels: approved, lgtm

#431 FIx failure of @OCP-69146
  tests/e2e/machine_pool_test.go
Labels: approved, lgtm

#436 Automate OCP-64906 :: Verify custom properties are set post cluster creation
  tests/e2e/verfication_post_day1_test.go
  tests/tf-manifests/rhcs/clusters/rosa-classic/main.tf
Labels: approved, lgtm

#422 Operators check before running postday1 and day2 checks
  tests/e2e/cluster_creation_test.go
  tests/utils/constants/constants.go
  tests/utils/openshift/console.go
Labels: approved, lgtm

#440 small machine pool tc fix
  tests/e2e/machine_pool_test.go
Labels: approved, lgtm

#441 OCM-5233 | fix: remove immutable from compute SGs
  provider/cluster/cluster_resource.go
  provider/clusterrosaclassic/cluster_rosa_classic_resource.go
  provider/machinepool/machine_pool_resource.go
Labels: approved, lgtm

#430 add rhcs_rosa_classic cluster import test case
  tests/e2e/idps_test.go
  tests/e2e/verfication_post_day1_test.go
Labels: approved, lgtm

#443 OCM-5016: Add an update test to autoscaler resource
  subsystem/cluster_autoscaler_resource_test.go
Labels: approved, jira/valid-reference, lgtm

#444 Splitting the tests
  subsystem/cluster_resource_rosa_create_test.go
  subsystem/cluster_resource_rosa_import_test.go
  subsystem/cluster_resource_rosa_upgrade_test.go
Labels: approved, lgtm

#446 OCM-5017: Autoscaler resource - Add validation for not negative values
  provider/clusterautoscaler/cluster_autoscaler_resource.go
  provider/clusterautoscaler/validators.go
  subsystem/cluster_autoscaler_resource_test.go
Labels: approved, jira/valid-reference, lgtm

#449 remove version check from ocp65684
  tests/e2e/verfication_post_day1_test.go
Labels: approved, lgtm

#450 fix ocp-68939
  tests/e2e/idps_test.go
Labels: approved, lgtm

#448 OCM-5345 | fix: Allow pod_pids_limit to be set via a variable
  provider/kubeletconfig/kubeletconfig_validators.go
  provider/kubeletconfig/kubeletconfig_validators_test.go
Labels: approved, lgtm

#429 OCM-4480: Account roles tests
  tests/ci/profile_handler.go
  tests/e2e/account_roles_test.go
  tests/tf-manifests/aws/add-account-roles/main.tf
  tests/tf-manifests/aws/add-account-roles/output.tf
  tests/tf-manifests/aws/add-account-roles/variables.tf
  tests/utils/constants/constants.go
Labels: approved, jira/valid-reference, lgtm

#442 OCM-4483: add unified_ path for account/operator case
  tests/ci/profile_handler.go
  tests/ci/profiles/tf_cluster_profile.yml
  tests/e2e/verfication_post_day1_test.go
  tests/tf-manifests/aws/account-roles/main.tf
  tests/tf-manifests/aws/account-roles/variables.tf
  tests/tf-manifests/aws/oidc-provider-operator-roles/main.tf
  tests/tf-manifests/aws/oidc-provider-operator-roles/variables.tf
  tests/tf-manifests/rhcs/clusters/rosa-classic/main.tf
  tests/tf-manifests/rhcs/clusters/rosa-classic/variables.tf
  tests/utils/exec/account-roles.go
  tests/utils/exec/cluster.go
  tests/utils/exec/oidc-provider-operator-roles.go
Labels: approved, jira/valid-reference, lgtm

#452 fix ocp-68939
  tests/e2e/idps_test.go
Labels: approved, lgtm

#445 OCM-5346 | fix: Do not wait for clusters in terminal states to be ready
  provider/common/cluster_waiter.go
  provider/kubeletconfig/kubeletconfig_resource.go
Labels: approved, lgtm

#453 add import negative tests
  tests/e2e/idps_test.go
  tests/e2e/verfication_post_day1_test.go
  tests/tf-manifests/rhcs/resource-import/main.tf
Labels: approved, lgtm

#457 OCM-5407: Validate Immutable attributes not changed after magic import
  provider/clusterrosaclassic/cluster_rosa_classic_resource.go
  provider/machinepool/machine_pool_resource.go
  subsystem/machine_pool_resource_test.go
Labels: approved, jira/valid-reference, lgtm

#459 OCM-5407: Validate Immutable attributes not changed after magic import
  provider/clusterrosaclassic/cluster_rosa_classic_resource.go
  provider/machinepool/machine_pool_resource.go
  subsystem/machine_pool_resource_test.go
Labels: approved, jira/valid-reference, lgtm

#461 fix random string function - the length was incorrect
  tests/e2e/negative_day_one_test.go
  tests/utils/helper/helper.go
Labels: approved, lgtm

#465 OCM-5260: Add docs about default/worker machine pool
  docs/guides/worker-machine-pool.md
  docs/resources/cluster_rosa_classic.md
  docs/resources/machine_pool.md
  provider/clusterrosaclassic/cluster_rosa_classic_resource.go
  provider/common/helpers.go
  provider/machinepool/machine_pool_resource.go
  templates/guides/worker-machine-pool.md.tmpl
Labels: approved, jira/valid-reference, lgtm

#463 OCM-5260: Add docs about default/worker machine pool
  docs/guides/worker-machine-pool.md
  docs/resources/cluster_rosa_classic.md
  docs/resources/machine_pool.md
  provider/clusterrosaclassic/cluster_rosa_classic_resource.go
  provider/common/helpers.go
  provider/machinepool/machine_pool_resource.go
  templates/guides/worker-machine-pool.md.tmpl
Labels: approved, jira/valid-reference, lgtm

#464 OCM-5285: MP labels can't be an empty map
  provider/machinepool/machine_pool_resource.go
  subsystem/machine_pool_resource_test.go
Labels: approved, jira/valid-reference, lgtm

#466 OCM-5260: Fix mistakes in the docs
  docs/guides/worker-machine-pool.md
  docs/resources/cluster_rosa_classic.md
  provider/clusterrosaclassic/cluster_rosa_classic_resource.go
  templates/guides/worker-machine-pool.md.tmpl
Labels: approved, jira/valid-reference, lgtm

#471 OCM-5383: Importing identity provider for a non exisiting cluster sho…
  provider/identityprovider/identity_provider_resource.go
  subsystem/identity_provider_resource_test.go
Labels: approved, jira/valid-reference, lgtm

#472 NO-ISSUE: Removed .vscode settings folder
  .gitignore
  .vscode/settings.json
Labels: approved, jira/valid-reference, lgtm
