Repository terraform-redhat/terraform-provider-rhcs, pull requests merged in 2023-11, with the labels that each got.

#365 adding gitlab/hub idp tests + fixes
  tests/ci/profiles/tf_cluster_profile.yml
  tests/e2e/idps_test.go
  tests/tf-manifests/rhcs/idps/github/main.tf
  tests/tf-manifests/rhcs/idps/github/output.tf
  tests/tf-manifests/rhcs/idps/github/variables.tf
  tests/tf-manifests/rhcs/idps/gitlab/output.tf
  tests/utils/constants/constants.go
  tests/utils/exec/idps.go
Labels: approved, lgtm

#334 OCM-4442: Moved kmsARN regexp validator to common lib
  go.mod
  go.sum
  internal/ocm/resource/cluster.go
  internal/ocm/resource/cluster_test.go
Labels: approved, jira/valid-reference, lgtm, ok-to-test

#371 Add TC OCP-65063 Create single-az machinepool for multi-az cluster
  tests/e2e/machine_pool_test.go
  tests/tf-manifests/rhcs/machine-pools/main.tf
  tests/tf-manifests/rhcs/machine-pools/variable.tf
  tests/utils/exec/machine-pools.go
Labels: approved, lgtm

#373 add google idp test case and additional fixes
  tests/e2e/idps_test.go
  tests/tf-manifests/rhcs/idps/google/main.tf
  tests/tf-manifests/rhcs/idps/google/variables.tf
  tests/utils/constants/constants.go
  tests/utils/exec/idps.go
Labels: approved, lgtm

#379 small fix for mp test
  tests/e2e/machine_pool_test.go
Labels: approved, lgtm

#382 OCM-4779: Fixing error in openid IDP
  provider/identityprovider/openid.go
  subsystem/identity_provider_resource_test.go
Labels: approved, jira/valid-reference, lgtm

#385 Fix a typo in error message of private_hosted_zone validator
  provider/clusterrosaclassic/validators.go
Labels: approved, lgtm

#387 support singleaz private profile
  tests/ci/profile_handler.go
  tests/ci/profiles/tf_cluster_profile.yml
  tests/e2e/machine_pool_test.go
  tests/e2e/verfication_post_day1_test.go
  tests/tf-manifests/rhcs/clusters/rosa-classic/main.tf
  tests/utils/constants/constants.go
  tests/utils/exec/cluster.go
Labels: approved, lgtm

#375 automate OCP-63777 & OCP-63134
  tests/ci/profile_handler.go
  tests/e2e/verfication_post_day1_test.go
  tests/utils/constants/constants.go
  tests/utils/helper/helper.go
Labels: approved, lgtm

#381 Adding OpenID Connect IDP config example
  docs/resources/identity_provider.md
  examples/create_identity_provider/README.md
  examples/create_identity_provider/openid/README.md
  examples/create_identity_provider/openid/main.tf
  examples/create_identity_provider/openid/variables.tf
  generate_example_usages/resources/rhcs_identity_provider/resource.tf
Labels: approved, lgtm

#393 Release v1.4.1
  CHANGELOG.md
Labels: approved, lgtm

#390 Support major version for TR
  tests/ci/profile_handler.go
  tests/ci/profiles/tf_cluster_profile.yml
Labels: approved, lgtm

#394 small fix to add private_link condition to avoid login command for idps
  tests/e2e/idps_test.go
Labels: approved, lgtm

#392 add idp negative tests - validate mandatory fields
  tests/e2e/idps_test.go
  tests/tf-manifests/rhcs/idps/github/main.tf
  tests/tf-manifests/rhcs/idps/github/variables.tf
  tests/tf-manifests/rhcs/idps/gitlab/main.tf
  tests/tf-manifests/rhcs/idps/ldap/main.tf
  tests/tf-manifests/rhcs/idps/ldap/variables.tf
  tests/utils/exec/idps.go
Labels: approved, lgtm

#391 single-az machinepool tc
  tests/e2e/machine_pool_test.go
  tests/tf-manifests/aws/vpc-tags/main.tf
  tests/tf-manifests/aws/vpc-tags/variables.tf
  tests/utils/constants/constants.go
  tests/utils/exec/tf-exec.go
  tests/utils/exec/vpc-tags.go
Labels: approved, lgtm

#397 OCM-4701 Automate OCP-65928 Cluster admin user during deployment
  tests/ci/profile_handler.go
  tests/ci/profiles/tf_cluster_profile.yml
  tests/e2e/verfication_post_day1_test.go
  tests/tf-manifests/rhcs/clusters/rosa-classic/main.tf
  tests/tf-manifests/rhcs/clusters/rosa-classic/variables.tf
  tests/utils/constants/constants.go
  tests/utils/exec/cluster.go
  tests/utils/helper/helper.go
Labels: approved, lgtm
