Repository terraform-redhat/terraform-provider-rhcs, pull requests merged in 2023-05, with the labels that each got.

#53 OCM-174: Added GitHub IDP provider attrs
  docs/resources/identity_provider.md
  provider/cluster_resource.go
  provider/cluster_rosa_classic_resource.go
  provider/common/attribute_validator.go
  provider/common/helpers.go
  provider/identity_provider_resource.go
  provider/identity_provider_state.go
  provider/idps/github.go
  provider/machine_pool_resource.go
  subsystem/identity_provider_resource_test.go
Labels: approved, jira/valid-reference, lgtm

#56 OCM-177: Move all identity providers to internal pkg
  docs/resources/identity_provider.md
  provider/identity_provider_resource.go
  provider/identity_provider_state.go
  provider/idps/github.go
  provider/idps/gitlab.go
  provider/idps/htpasswd.go
  provider/idps/ldap.go
  provider/idps/openid.go
Labels: approved, jira/valid-reference, lgtm

#59 OCM-201: Add support for mapping_method
  provider/identity_provider_resource.go
  provider/identity_provider_state.go
  provider/idps/mapping_method_validator.go
  subsystem/identity_provider_resource_test.go
Labels: approved, jira/valid-reference, lgtm

#61 add osherdp to repo approvers list
  OWNERS
Labels: approved, lgtm

#62 fix ci/e2e code to get local ocm provider
  ci/e2e/account_roles_files/README.md
  ci/e2e/account_roles_files/main.tf
  ci/e2e/account_roles_files/variables.tf
  ci/e2e/terraform_provider_ocm_files/main.tf
  ci/e2e/terraform_provider_ocm_files/variables.tf
Labels: approved, lgtm

#63 revert token, url var names
  ci/e2e/account_roles_files/main.tf
  ci/e2e/account_roles_files/variables.tf
  ci/e2e/terraform_provider_ocm_files/main.tf
  ci/e2e/terraform_provider_ocm_files/variables.tf
Labels: approved, lgtm

#64 OCM-176: Support IDP with Google user
  provider/common/helpers.go
  provider/identity_provider_resource.go
  provider/identity_provider_state.go
  provider/idps/google.go
  subsystem/identity_provider_resource_test.go
Labels: approved, jira/valid-reference, lgtm

#57 OCM-136: Allow specifying channel group name
  go.mod
  go.sum
  provider/cluster_rosa_classic_resource.go
  provider/cluster_rosa_classic_resource_test.go
  provider/cluster_rosa_classic_state.go
  subsystem/cluster_resource_rosa_test.go
Labels: approved, jira/valid-reference, lgtm, ok-to-test

#67 Fix e2e flow missing variables
  Makefile
  ci/e2e/terraform_provider_ocm_fullcycle_test.go
Labels: approved, lgtm

#66 OCM-141: Terraform for IMDSv2 support
  docs/resources/cluster_rosa_classic.md
  docs/resources/machine_pool.md
  go.mod
  go.sum
  provider/cluster_rosa_classic_resource.go
  provider/cluster_rosa_classic_resource_test.go
  provider/cluster_rosa_classic_state.go
  provider/common/helpers.go
  provider/enum_value_validator.go
  subsystem/cluster_resource_rosa_test.go
Labels: approved, jira/valid-reference, lgtm, ok-to-test

#69 SDE-2990 | Fixing a typo in account_roles README.md file
  examples/create_rosa_cluster/create_rosa_sts_cluster/classic_sts/account_roles/README.md
Labels: approved, lgtm

#70 Fixing issue with empty aws_http_tokens in ocm response
  provider/cluster_rosa_classic_resource.go
Labels: approved, lgtm, needs-ok-to-test

#71 change cluster_name prefix to be "ci-ocm-tf-"
  ci/e2e/terraform_provider_ocm_fullcycle_test.go
Labels: approved, lgtm

#44 refactor cluster_name, region and az into vars
  examples/create_rosa_cluster/create_rosa_sts_cluster/classic_sts/cluster/main.tf
  examples/create_rosa_cluster/create_rosa_sts_cluster/classic_sts/cluster/variables.tf
Labels: approved, lgtm

#73 fix account_roles to extract version from extended openshift_version
  ci/e2e/account_roles_files/main.tf
  ci/e2e/terraform_provider_ocm_files/main.tf
  ci/e2e/terraform_provider_ocm_files/variables.tf
Labels: approved, lgtm

#75 add Asher to OWNERS
  OWNERS
Labels: approved, lgtm

#76 restore back version format
  ci/e2e/terraform_provider_ocm_files/main.tf
Labels: approved

#78 Fix missing token variable when destroying roles
  ci/e2e/terraform_provider_ocm_fullcycle_test.go
Labels: approved, lgtm

#72 OCM-335: Added provider version and commit to cluster properties
  provider/cluster_rosa_classic_resource.go
  provider/cluster_rosa_classic_resource_test.go
  provider/cluster_rosa_classic_state.go
  subsystem/cluster_resource_rosa_test.go
Labels: approved, jira/valid-reference, lgtm

#80 OCM-141: Changing parameter name from HttpTokensState to Ec2MetadataHttpTokens
  go.mod
  go.sum
  provider/cluster_rosa_classic_resource.go
  provider/cluster_rosa_classic_resource_test.go
  provider/cluster_rosa_classic_state.go
  subsystem/cluster_resource_rosa_test.go
Labels: approved, jira/valid-reference, lgtm

#79 OCM-355: Set proper UserAgent tf version + minor indent fix
  provider/cluster_rosa_classic_resource.go
  subsystem/cluster_resource_rosa_test.go
Labels: approved, jira/valid-reference, lgtm

#82 OCM-239: day2 enable/disable user workload monitoring
  provider/cluster_rosa_classic_resource.go
  provider/common/helpers.go
  subsystem/cluster_resource_rosa_test.go
Labels: approved, jira/valid-reference, lgtm

#84 Add instructions to README.md on how to get binary from image.
  README.md
Labels: approved, lgtm

#87 OCM-274: Added 2 make targets
  .gitignore
  Makefile
  README.md
  ci/apply_folder.sh
  ci/destroy_folder.sh
  ci/post_apply_prow_setup.sh
  ci/setup_prow_env.sh
Labels: approved, jira/valid-reference, lgtm

#89 Fixed typos in README
  README.md
Labels: approved, lgtm

#90 OCM-759: add error to "rosa_operator_roles_data_source" in case get stsOperatorRolesList failure
  provider/rosa_operator_roles_data_source.go
Labels: approved, jira/valid-reference, lgtm

#91 Add myself (nirarg) to OWNERS file
  OWNERS
Labels: approved, lgtm
