Repository terraform-redhat/terraform-provider-rhcs, pull requests merged in 2023-07, with the labels that each got.

#151 Updated documentation for modifying machine pools
  docs/modify-cluster.md
  docs/resources/machine_pool.md
  examples/create_machine_pool/README.md
  examples/create_machine_pool/main.tf
  examples/create_machine_pool/variables.tf
  examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/cluster_with_managed_oidc_config/main.tf
  examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/cluster_with_managed_oidc_config/variables.tf
  examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/cluster_with_unmanaged_oidc_config/main.tf
  examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/cluster_with_unmanaged_oidc_config/variables.tf
  provider/machine_pool_resource.go
Labels: documentation, approved, lgtm

#171 OCM-2595: fix guides files publish to registry
  docs/guides/machine-pool.md
  docs/guides/terraform-vars.md
  docs/guides/upgrading-cluster.md
Labels: approved, jira/valid-reference, lgtm

#170 OCM-2593: Support for cluster properties update/delete
  provider/cluster_rosa_classic_resource.go
  subsystem/cluster_resource_rosa_test.go
Labels: approved, jira/valid-reference, lgtm

#172 OCM-2549: Add notice to user that operator policies are created as part of the account roles example
  examples/create_rosa_cluster/create_rosa_sts_cluster/classic_sts/account_roles/README.md
Labels: approved, jira/valid-reference, lgtm

#173 OCM-2627: change ocm_machine_types to rhcs_machine_types in docs
  docs/resources/cluster_rosa_classic.md
  docs/resources/machine_pool.md
Labels: approved, jira/valid-reference, lgtm

#174 Refactoring the cluster properties validator
  provider/cluster_rosa_classic_resource.go
Labels: approved, lgtm

#133 Update README.md for using new binary image.
  Makefile
  README.md
Labels: approved, lgtm

#175 Add open issues to docs
  docs/index.md
Labels: approved, lgtm

#176 Rename in the example output of cluster sts
  examples/create_rosa_cluster/create_rosa_sts_cluster/classic_sts/cluster/output.tf
Labels: approved, lgtm

#177 OCM-2655: Fix gitlab to github in example
  examples/create_identity_provider/github/main.tf
Labels: approved, jira/valid-reference, lgtm

#142 OCM-2493: Add support for 1AZ pool in mAZ cluster
  .gitignore
  provider/machine_pool_resource.go
  provider/machine_pool_state.go
  subsystem/machine_pool_resource_test.go
Labels: approved, jira/valid-reference, lgtm

#181 Fix a minor space indentation issue
  examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/cluster_with_managed_oidc_config/variables.tf
Labels: approved, lgtm, ok-to-test

#185 OCM-2456: Change examples folders
  README.md
  docs/index.md
  examples/create_account_roles/README.md
  examples/create_account_roles/main.tf
  examples/create_account_roles/variables.tf
  examples/create_rosa_sts_cluster/README.md
  examples/create_rosa_sts_cluster/classic_sts/cluster/README.md
  examples/create_rosa_sts_cluster/classic_sts/cluster/main.tf
  examples/create_rosa_sts_cluster/classic_sts/cluster/output.tf
  examples/create_rosa_sts_cluster/classic_sts/cluster/variables.tf
  examples/create_rosa_sts_cluster/oidc_configuration/cluster_with_managed_oidc_config/README.md
  examples/create_rosa_sts_cluster/oidc_configuration/cluster_with_managed_oidc_config/main.tf
  examples/create_rosa_sts_cluster/oidc_configuration/cluster_with_managed_oidc_config/output.tf
  examples/create_rosa_sts_cluster/oidc_configuration/cluster_with_managed_oidc_config/variables.tf
  examples/create_rosa_sts_cluster/oidc_configuration/cluster_with_unmanaged_oidc_config/README.md
  examples/create_rosa_sts_cluster/oidc_configuration/cluster_with_unmanaged_oidc_config/main.tf
  examples/create_rosa_sts_cluster/oidc_configuration/cluster_with_unmanaged_oidc_config/output.tf
  examples/create_rosa_sts_cluster/oidc_configuration/cluster_with_unmanaged_oidc_config/variables.tf
  examples/create_rosa_sts_cluster/oidc_configuration/oidc_provider/README.md
  examples/create_rosa_sts_cluster/oidc_configuration/oidc_provider/main.tf
  examples/create_rosa_sts_cluster/oidc_configuration/oidc_provider/output.tf
  examples/create_rosa_sts_cluster/oidc_configuration/oidc_provider/variables.tf
Labels: approved, jira/valid-reference, lgtm

#189 Fix space indentation
  examples/create_machine_pool/variables.tf
Labels: approved, lgtm

#192 Unmanaged OIDC cluster example: Remove "installer_role_arn" and create it locally
  examples/create_rosa_sts_cluster/oidc_configuration/cluster_with_unmanaged_oidc_config/README.md
  examples/create_rosa_sts_cluster/oidc_configuration/cluster_with_unmanaged_oidc_config/main.tf
  examples/create_rosa_sts_cluster/oidc_configuration/cluster_with_unmanaged_oidc_config/variables.tf
Labels: approved, lgtm

#191 OCM-2646: Recreate IDP if it was deleted not from tf
  provider/identity_provider_resource.go
  subsystem/identity_provider_resource_test.go
Labels: approved, jira/valid-reference, lgtm

#186 OCM-2644: Recreate machine pool if it was deleted from other client.
  provider/machine_pool_resource.go
  subsystem/machine_pool_resource_test.go
Labels: approved, jira/valid-reference, lgtm

#190 OCM-2666: Remove AWS validations from rosa_cluster resource
  docs/index.md
  provider/cluster_rosa_classic_resource.go
  subsystem/cluster_resource_rosa_test.go
Labels: approved, jira/valid-reference, lgtm

#194 OCM-2443: Improve error message
  provider/machine_pool_resource.go
Labels: approved, jira/valid-reference, lgtm

#193 OCM-2361: Support generated account_role_prefix
  ci/e2e/account_roles_files/main.tf
  ci/e2e/oidc_configuration/cluster_with_managed_oidc_config/main.tf
  ci/e2e/oidc_configuration/cluster_with_unmanaged_oidc_config/main.tf
  examples/create_account_roles/README.md
  examples/create_account_roles/main.tf
  examples/create_account_roles/output.tf
  examples/create_account_roles/variables.tf
  examples/create_rosa_sts_cluster/classic_sts/cluster/main.tf
  examples/create_rosa_sts_cluster/oidc_configuration/oidc_provider/main.tf
Labels: approved, jira/valid-reference, lgtm

#196 OCM-2645: Recreate cluster if it was deleted from other client
  provider/cluster_rosa_classic_resource.go
  provider/cluster_waiter_resource.go
  subsystem/cluster_resource_rosa_test.go
  subsystem/cluster_waiter_test.go
Labels: approved, jira/valid-reference, lgtm

#180 Finish tests structure folders creation
  tests/OWNERS
  tests/README.md
  tests/e2e/cluster_creation.go
  tests/e2e/init_test.go
  tests/prow_ci.sh
  tests/tf-manifests/README.md
  tests/tf-manifests/aws/account-roles/main.tf
  tests/tf-manifests/aws/account-roles/variables.tf
  tests/tf-manifests/aws/vpc/main.tf
  tests/tf-manifests/aws/vpc/output.tf
  tests/tf-manifests/aws/vpc/variables.tf
  tests/tf-manifests/rhcs/clusters/rosa-classic/main.tf
  tests/tf-manifests/rhcs/clusters/rosa-classic/output.tf
  tests/tf-manifests/rhcs/clusters/rosa-classic/variables.tf
  tests/tf-manifests/rhcs/idps/github/main.tf
  tests/tf-manifests/rhcs/idps/github/output.tf
  tests/tf-manifests/rhcs/idps/github/variables.tf
  tests/tf-manifests/rhcs/idps/gitlab/main.tf
  tests/tf-manifests/rhcs/idps/gitlab/output.tf
  tests/tf-manifests/rhcs/idps/gitlab/variables.tf
  tests/tf-manifests/rhcs/idps/google/main.tf
  tests/tf-manifests/rhcs/idps/google/output.tf
  tests/tf-manifests/rhcs/idps/google/variables.tf
  tests/tf-manifests/rhcs/idps/htpasswd/main.tf
  tests/tf-manifests/rhcs/idps/htpasswd/output.tf
  tests/tf-manifests/rhcs/idps/htpasswd/variables.tf
  tests/tf-manifests/rhcs/idps/ldap/main.tf
  tests/tf-manifests/rhcs/idps/ldap/output.tf
  tests/tf-manifests/rhcs/idps/ldap/variables.tf
  tests/tf-manifests/rhcs/idps/openid/main.tf
  tests/tf-manifests/rhcs/idps/openid/output.tf
  tests/tf-manifests/rhcs/idps/openid/variables.tf
  tests/tf-manifests/rhcs/machine-pools/main.tf
  tests/tf-manifests/rhcs/machine-pools/output.tf
  tests/tf-manifests/rhcs/machine-pools/variable.tf
  tests/utils/constants/constants.go
  tests/utils/helper/helper.go
Labels: approved, lgtm, ok-to-test

#197 OCM-2702: Add ldflag section to build in goreleaser.yaml
  .goreleaser.yaml
Labels: approved, jira/valid-reference, lgtm

#201 Fix a minor typo on docs index.md
  docs/index.md
Labels: approved, lgtm

#203 OCM-2415: Fixing the example of list_versions usage
  ci/e2e/account_roles_files/main.tf
  ci/e2e/oidc_configuration/cluster_with_managed_oidc_config/main.tf
  ci/e2e/oidc_configuration/cluster_with_unmanaged_oidc_config/main.tf
  examples/create_account_roles/main.tf
  examples/create_rosa_sts_cluster/classic_sts/cluster/main.tf
  examples/create_rosa_sts_cluster/oidc_configuration/oidc_provider/main.tf
  examples/list_versions/main.tf
  examples/list_versions/output.tf
  examples/list_versions/variables.tf
  tests/tf-manifests/aws/account-roles/main.tf
  tests/tf-manifests/rhcs/clusters/rosa-classic/main.tf
Labels: approved, jira/valid-reference, lgtm

#202 OCM-2769: change to explicit aws credentials
  .gitignore
  ci/e2e/account_roles_files/main.tf
  ci/e2e/account_roles_files/variables.tf
  ci/e2e/oidc_configuration/cluster_with_managed_oidc_config/main.tf
  ci/e2e/oidc_configuration/cluster_with_managed_oidc_config/variables.tf
  ci/e2e/oidc_configuration/cluster_with_unmanaged_oidc_config/main.tf
  ci/e2e/oidc_configuration/cluster_with_unmanaged_oidc_config/variables.tf
  ci/e2e/terraform_provider_ocm_files/main.tf
  ci/e2e/terraform_provider_ocm_files/variables.tf
  ci/setup_prow_env.sh
Labels: approved, jira/valid-reference, lgtm

#209 OCM-2415: use rosa-sts v0.0.12 - openshift version validation
  ci/e2e/account_roles_files/main.tf
  ci/e2e/oidc_configuration/cluster_with_managed_oidc_config/main.tf
  ci/e2e/oidc_configuration/cluster_with_unmanaged_oidc_config/main.tf
  examples/create_account_roles/README.md
  examples/create_account_roles/main.tf
  examples/create_account_roles/variables.tf
  examples/create_rosa_sts_cluster/classic_sts/cluster/main.tf
  examples/create_rosa_sts_cluster/oidc_configuration/oidc_provider/main.tf
  tests/tf-manifests/rhcs/clusters/rosa-classic/main.tf
Labels: approved, jira/valid-reference, lgtm

#210 Prepare release v1.2.0-prerelease.1
  docs/index.md
Labels: approved, lgtm

#211 OCM-2670: Fix GitHub IDP example
  examples/create_identity_provider/github/main.tf
  examples/create_identity_provider/github/variables.tf
Labels: approved, jira/valid-reference, lgtm

#213 link update
  README.md
Labels: approved, lgtm

#208 Ci profiles
  tests/ci/profiles/tf_cluster_profile.yml
  tests/tf-manifests/aws/account-roles/main.tf
  tests/tf-manifests/aws/account-roles/variables.tf
  tests/tf-manifests/aws/vpc/main.tf
  tests/tf-manifests/rhcs/clusters/rosa-classic/main.tf
  tests/tf-manifests/rhcs/clusters/rosa-classic/variables.tf
  tests/tf-manifests/rhcs/idps/github/main.tf
  tests/tf-manifests/rhcs/idps/gitlab/main.tf
  tests/tf-manifests/rhcs/idps/gitlab/variables.tf
  tests/tf-manifests/rhcs/idps/google/main.tf
  tests/tf-manifests/rhcs/idps/google/variables.tf
  tests/tf-manifests/rhcs/idps/htpasswd/main.tf
  tests/tf-manifests/rhcs/idps/htpasswd/variables.tf
  tests/tf-manifests/rhcs/idps/ldap/main.tf
  tests/tf-manifests/rhcs/idps/ldap/variables.tf
  tests/tf-manifests/rhcs/idps/openid/main.tf
  tests/tf-manifests/rhcs/idps/openid/variables.tf
  tests/tf-manifests/rhcs/machine-pools/main.tf
Labels: approved, lgtm

#184 Various Terraform updates
  README.md
  docs/guides/upgrading-cluster.md
  docs/index.md
  examples/create_account_roles/README.md
  examples/create_rosa_sts_cluster/oidc_configuration/cluster_with_managed_oidc_config/README.md
  examples/create_rosa_sts_cluster/oidc_configuration/cluster_with_unmanaged_oidc_config/README.md
Labels: approved, lgtm

#214 Add default for ec2_metadata_http_tokens
  provider/cluster_rosa_classic_resource.go
  provider/cluster_rosa_classic_resource_test.go
  subsystem/cluster_resource_rosa_test.go
Labels: approved, lgtm
