Repository terraform-redhat/terraform-provider-rhcs, pull requests merged in 2023-06, with the labels that each got.

#96 Store .tf files in artifact dir on PROW runs
  ci/apply_folder.sh
  ci/destroy_folder.sh
  ci/setup_prow_env.sh
Labels: approved, lgtm

#98 add more debug level to provider and bash wrapper
  ci/apply_folder.sh
  ci/destroy_folder.sh
  ci/post_apply_prow_setup.sh
  ci/setup_prow_env.sh
Labels: approved, lgtm

#99 Allow users to set cluster_name, cloud_region and hosted_zones
  examples/create_rosa_cluster/create_rosa_iam_cluster/main.tf
  examples/create_rosa_cluster/create_rosa_sts_cluster/classic_sts/account_roles/main.tf
  examples/create_rosa_cluster/create_rosa_sts_cluster/classic_sts/account_roles/variables.tf
  examples/create_rosa_cluster/create_rosa_sts_cluster/classic_sts/cluster/main.tf
  examples/create_rosa_cluster/create_rosa_sts_cluster/classic_sts/cluster/output.tf
  examples/create_rosa_cluster/create_rosa_sts_cluster/classic_sts/cluster/variables.tf
  examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/cluster_with_managed_oidc_config/main.tf
  examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/cluster_with_managed_oidc_config/output.tf
  examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/cluster_with_managed_oidc_config/variables.tf
  examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/cluster_with_unmanaged_oidc_config/main.tf
  examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/cluster_with_unmanaged_oidc_config/output.tf
  examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/cluster_with_unmanaged_oidc_config/variables.tf
Labels: approved, lgtm

#102 Examples: Move OIDC provider creation to different module
  examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/cluster_with_managed_oidc_config/main.tf
  examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/cluster_with_managed_oidc_config/output.tf
  examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/cluster_with_unmanaged_oidc_config/main.tf
  examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/cluster_with_unmanaged_oidc_config/output.tf
  examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/oidc_provider/README.md
  examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/oidc_provider/main.tf
  examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/oidc_provider/output.tf
  examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/oidc_provider/variables.tf
Labels: approved, lgtm

#97 OCM-1018: Change provider logger to tflog
  go.mod
  go.sum
  logging/logging.go
  provider/cloud_providers_data_source.go
  provider/cluster_resource.go
  provider/cluster_rosa_classic_resource.go
  provider/cluster_rosa_classic_resource_test.go
  provider/cluster_waiter_resource.go
  provider/group_membership_resource.go
  provider/groups_data_source.go
  provider/identity_provider_resource.go
  provider/machine_pool_resource.go
  provider/machine_types_data_source.go
  provider/ocm_policies_data_source.go
  provider/provider.go
  provider/rosa_oidc_config_input_resource.go
  provider/rosa_oidc_config_resource.go
  provider/rosa_operator_roles_data_source.go
  provider/value_cannot_be_changed_modifier.go
  provider/versions_data_source.go
Labels: approved, jira/valid-reference, lgtm

#103 change TF_LOG to info
  ci/apply_folder.sh
Labels: approved, lgtm

#104 OCM-2237: Add support for adding path to account roles in creation
  examples/create_rosa_cluster/create_rosa_sts_cluster/classic_sts/account_roles/README.md
  examples/create_rosa_cluster/create_rosa_sts_cluster/classic_sts/account_roles/main.tf
  examples/create_rosa_cluster/create_rosa_sts_cluster/classic_sts/account_roles/variables.tf
  examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/cluster_with_managed_oidc_config/README.md
  examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/cluster_with_managed_oidc_config/main.tf
  examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/cluster_with_managed_oidc_config/variables.tf
  examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/cluster_with_unmanaged_oidc_config/README.md
  examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/cluster_with_unmanaged_oidc_config/main.tf
  examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/cluster_with_unmanaged_oidc_config/variables.tf
  examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/oidc_provider/main.tf
Labels: approved, jira/valid-reference, lgtm

#106 OCM-1026: Improve "Not supported version" error mesage
  provider/cluster_rosa_classic_resource.go
Labels: approved, jira/valid-reference, lgtm

#107 OCM-2289: Add the option for tagging AWS resources in the example files
  examples/create_rosa_cluster/create_rosa_sts_cluster/classic_sts/account_roles/README.md
  examples/create_rosa_cluster/create_rosa_sts_cluster/classic_sts/account_roles/main.tf
  examples/create_rosa_cluster/create_rosa_sts_cluster/classic_sts/account_roles/variables.tf
  examples/create_rosa_cluster/create_rosa_sts_cluster/classic_sts/cluster/README.md
  examples/create_rosa_cluster/create_rosa_sts_cluster/classic_sts/cluster/main.tf
  examples/create_rosa_cluster/create_rosa_sts_cluster/classic_sts/cluster/variables.tf
  examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/cluster_with_managed_oidc_config/README.md
  examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/cluster_with_managed_oidc_config/main.tf
  examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/cluster_with_managed_oidc_config/variables.tf
  examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/cluster_with_unmanaged_oidc_config/README.md
  examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/cluster_with_unmanaged_oidc_config/main.tf
  examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/cluster_with_unmanaged_oidc_config/variables.tf
  examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/oidc_provider/README.md
  examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/oidc_provider/main.tf
  examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/oidc_provider/variables.tf
Labels: approved, jira/valid-reference, lgtm

#101 OCM-2185: remove ROSA non-STS terraform content from provider repo
  examples/create_rosa_cluster/create_rosa_iam_cluster/README.md
  examples/create_rosa_cluster/create_rosa_iam_cluster/main.tf
  examples/create_simple_cluster/README.md
  examples/create_simple_cluster/main.tf
Labels: approved, jira/valid-reference, lgtm

#116 name change from ocm
  README.md
Labels: approved, lgtm

#115 Pass non-default channel when looking for upgrades
  provider/cluster_rosa_classic_resource.go
Labels: approved, lgtm

#117 OCM-2342: Adding IDP examples and docs phase 1
  examples/create_gitlab_identity_provider/README.md
  examples/create_identity_provider/github/README.md
  examples/create_identity_provider/github/main.tf
  examples/create_identity_provider/github/terraform.tfvars
  examples/create_identity_provider/gitlab/README.md
  examples/create_identity_provider/gitlab/main.tf
  examples/create_identity_provider/gitlab/terraform.tfvars
  examples/create_identity_provider/google/README.md
  examples/create_identity_provider/google/main.tf
  examples/create_identity_provider/google/terraform.tfvars
  examples/create_identity_provider/htpasswd/README.md
  examples/create_identity_provider/htpasswd/main.tf
  examples/create_identity_provider/htpasswd/terraform.tfvars
Labels: approved, jira/valid-reference, lgtm

#88 Updating the Index and README files
  README.md
  docs/index.md
  docs/resources/cluster_rosa_classic.md
  docs/resources/identity_provider.md
  provider/cluster_rosa_classic_resource.go
  provider/provider.go
Labels: approved, lgtm, ok-to-test

#113 Update example docs
  examples/create_rosa_cluster/create_rosa_sts_cluster/classic_sts/account_roles/README.md
  examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/cluster_with_managed_oidc_config/README.md
  examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/cluster_with_unmanaged_oidc_config/README.md
Labels: approved, lgtm

#120 OCM-2420: LDAP IDP fixes
  docs/resources/identity_provider.md
  provider/common/helpers.go
  provider/identity_provider_resource.go
  provider/idps/ldap.go
  subsystem/identity_provider_resource_test.go
Labels: approved, jira/valid-reference, lgtm

#123 OCM-2342: Adding IDP examples and docs phase 2
  examples/create_identity_provider/ldap/README.md
  examples/create_identity_provider/ldap/main.tf
  examples/create_identity_provider/ldap/terraform.tfvars
Labels: approved, jira/valid-reference, lgtm

#119 OCM-2254: Add Dockerfiles for ARM and AMD64 binaries
  build/ci-tf-bin.Dockerfile
Labels: approved, jira/valid-reference, lgtm

#125 Machine Pool creation: add example
  examples/create_machine_pool/README.md
  examples/create_machine_pool/main.tf
  examples/create_machine_pool/variables.tf
Labels: approved, lgtm

#126 Remove unsupported resources docs
  docs/resources/cluster.md
  docs/resources/group_membership.md
Labels: approved, lgtm

#122 Day 2 Terraform Tasks
  README.md
  examples/create_identity_provider/README.md
  examples/create_identity_provider/github/README.md
  examples/create_identity_provider/gitlab/README.md
  examples/create_identity_provider/google/README.md
  examples/create_identity_provider/htpasswd/README.md
  examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/cluster_with_managed_oidc_config/README.md
  examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/cluster_with_unmanaged_oidc_config/README.md
Labels: approved, lgtm

#128 v1.0.2: Add release notes
  CHANGELOG.md
Labels: approved, lgtm

#129 Improve example links in the registry docs
  docs/index.md
Labels: approved, lgtm

#114 Add an options to set version in oidc clusters
  examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/cluster_with_managed_oidc_config/main.tf
  examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/cluster_with_managed_oidc_config/variables.tf
  examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/cluster_with_unmanaged_oidc_config/main.tf
  examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/cluster_with_unmanaged_oidc_config/variables.tf
Labels: approved, lgtm

#131 OCM-2406: Fixed oidc-provider example to use same aws region
  examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/oidc_provider/main.tf
Labels: approved, jira/valid-reference, lgtm

#132 Fixing indentation in index.md file
  docs/index.md
  docs/resources/cluster_rosa_classic.md
Labels: approved, lgtm

#130 OCM-2342: Updated examples
  ci/e2e/oidc_configuration/cluster_with_managed_oidc_config/main.tf
  examples/create_identity_provider/github/README.md
  examples/create_identity_provider/github/main.tf
  examples/create_identity_provider/github/terraform.tfvars
  examples/create_identity_provider/github/variables.tf
  examples/create_identity_provider/gitlab/README.md
  examples/create_identity_provider/gitlab/main.tf
  examples/create_identity_provider/gitlab/terraform.tfvars
  examples/create_identity_provider/gitlab/variables.tf
  examples/create_identity_provider/google/README.md
  examples/create_identity_provider/google/main.tf
  examples/create_identity_provider/google/terraform.tfvars
  examples/create_identity_provider/google/variables.tf
  examples/create_identity_provider/htpasswd/README.md
  examples/create_identity_provider/htpasswd/main.tf
  examples/create_identity_provider/htpasswd/terraform.tfvars
  examples/create_identity_provider/htpasswd/variables.tf
  examples/create_identity_provider/ldap/README.md
  examples/create_identity_provider/ldap/main.tf
  examples/create_identity_provider/ldap/terraform.tfvars
  examples/create_identity_provider/ldap/variables.tf
Labels: approved, jira/valid-reference, lgtm

#127 Created new topics on Terraform vars and modifying machine pools.
  README.md
  docs/index.md
  docs/modify-cluster.md
  docs/terraform-vars.md
  examples/create_identity_provider/github/README.md
  examples/create_identity_provider/gitlab/README.md
  examples/create_identity_provider/google/README.md
  examples/create_identity_provider/htpasswd/README.md
  examples/create_identity_provider/ldap/README.md
  examples/create_machine_pool/README.md
  examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/cluster_with_managed_oidc_config/README.md
  examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/cluster_with_unmanaged_oidc_config/README.md
Labels: approved, lgtm

#124 OCM-2428: Remove openshift-v prefix from create cluster version attribute
  ci/e2e/oidc_configuration/cluster_with_managed_oidc_config/main.tf
  ci/e2e/oidc_configuration/cluster_with_unmanaged_oidc_config/main.tf
  docs/resources/cluster_rosa_classic.md
  examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/cluster_with_managed_oidc_config/variables.tf
  examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/cluster_with_unmanaged_oidc_config/variables.tf
  provider/cluster_rosa_classic_resource.go
  provider/cluster_rosa_classic_resource_test.go
  subsystem/cluster_resource_rosa_test.go
Labels: approved, jira/valid-reference, lgtm

#136 Creating upgrading documentation
  README.md
  docs/index.md
  docs/upgrading-cluster.md
  examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/cluster_with_managed_oidc_config/main.tf
  examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/cluster_with_managed_oidc_config/variables.tf
Labels: approved, lgtm

#135 OCM-2460: Added update/remove taints from machine pool
  provider/machine_pool_resource.go
  subsystem/machine_pool_resource_test.go
Labels: approved, jira/valid-reference, lgtm

#137 Remove acks_for variable added by mistake to example
  docs/upgrading-cluster.md
  examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/cluster_with_managed_oidc_config/main.tf
  examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/cluster_with_managed_oidc_config/variables.tf
Labels: approved, lgtm

#138 OCM-2237: Fix path also to be used for the operator roles creation
  docs/upgrading-cluster.md
  examples/create_rosa_cluster/create_rosa_sts_cluster/classic_sts/account_roles/main.tf
  examples/create_rosa_cluster/create_rosa_sts_cluster/classic_sts/account_roles/variables.tf
  examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/cluster_with_managed_oidc_config/main.tf
  examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/cluster_with_managed_oidc_config/variables.tf
  examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/cluster_with_unmanaged_oidc_config/main.tf
  examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/cluster_with_unmanaged_oidc_config/variables.tf
  examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/oidc_provider/main.tf
  examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/oidc_provider/variables.tf
Labels: approved, jira/valid-reference, lgtm

#139 Fix examples to use specific version of the module
  ci/e2e/account_roles_files/main.tf
  ci/e2e/oidc_configuration/cluster_with_managed_oidc_config/main.tf
  ci/e2e/oidc_configuration/cluster_with_unmanaged_oidc_config/main.tf
  ci/e2e/terraform_provider_ocm_files/main.tf
  examples/create_rosa_cluster/create_rosa_sts_cluster/classic_sts/account_roles/main.tf
  examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/oidc_provider/main.tf
Labels: approved, lgtm

#141 Updated README and Index for limitations and policies.
  README.md
  docs/index.md
Labels: approved, lgtm

#140 OCM-2489: Fix useSpotInstances attribute usage
  provider/machine_pool_resource.go
  subsystem/machine_pool_resource_test.go
Labels: approved, jira/valid-reference, lgtm

#145 Updated docs. Using the new rhcs name
  docs/data-sources/cloud_providers.md
  docs/data-sources/groups.md
  docs/data-sources/machine_types.md
  docs/data-sources/policies.md
  docs/data-sources/rosa_operator_roles.md
  docs/data-sources/versions.md
  docs/index.md
  docs/resources/cluster_rosa_classic.md
  docs/resources/cluster_wait.md
  docs/resources/identity_provider.md
  docs/resources/machine_pool.md
  docs/resources/rosa_oidc_config.md
  docs/resources/rosa_oidc_config_input.md
Labels: approved, lgtm

#148 CI: Updated module version 0.0.8 -> 0.0.9
  ci/e2e/account_roles_files/main.tf
  ci/e2e/oidc_configuration/cluster_with_managed_oidc_config/main.tf
  ci/e2e/oidc_configuration/cluster_with_unmanaged_oidc_config/main.tf
  examples/create_rosa_cluster/create_rosa_sts_cluster/classic_sts/account_roles/main.tf
  examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/oidc_provider/main.tf
Labels: approved, lgtm

#150 Examples: Updated to the upcoming 1.0.5 release
  examples/create_ccs_cluster/main.tf
  examples/create_identity_provider/github/main.tf
  examples/create_identity_provider/gitlab/main.tf
  examples/create_identity_provider/google/main.tf
  examples/create_identity_provider/htpasswd/main.tf
  examples/create_identity_provider/ldap/main.tf
  examples/create_machine_pool/main.tf
  examples/create_machine_pool/variables.tf
  examples/create_rosa_cluster/create_rosa_sts_cluster/classic_sts/account_roles/main.tf
  examples/create_rosa_cluster/create_rosa_sts_cluster/classic_sts/account_roles/variables.tf
  examples/create_rosa_cluster/create_rosa_sts_cluster/classic_sts/cluster/main.tf
  examples/create_rosa_cluster/create_rosa_sts_cluster/classic_sts/cluster/variables.tf
  examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/cluster_with_managed_oidc_config/main.tf
  examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/cluster_with_managed_oidc_config/variables.tf
  examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/cluster_with_unmanaged_oidc_config/main.tf
  examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/cluster_with_unmanaged_oidc_config/variables.tf
  examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/oidc_provider/main.tf
  examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/oidc_provider/variables.tf
  examples/list_cloud_providers/main.tf
  examples/list_machine_types/main.tf
  examples/list_versions/main.tf
Labels: approved, lgtm, ok-to-test

#152 OCM-2523: Support to edit/delete labels of secondary machine pool
  provider/machine_pool_resource.go
  subsystem/machine_pool_resource_test.go
Labels: approved, jira/valid-reference, lgtm

#153 Release 1.0.5
  CHANGELOG.md
Labels: approved, lgtm

#155 Update README.md
  README.md
Labels: approved, lgtm

#156 Update index.md
  docs/index.md
Labels: approved, lgtm

#158 Update terraform-vars.md
  docs/terraform-vars.md
Labels: approved, lgtm

#161 Update README.md
  examples/create_machine_pool/README.md
Labels: approved, lgtm

#159 Update upgrading-cluster.md
  docs/upgrading-cluster.md
Labels: approved, lgtm

#160 Update README.md
  examples/create_identity_provider/README.md
Labels: approved, lgtm

#163 Update README.md
  examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/cluster_with_unmanaged_oidc_config/README.md
Labels: approved, lgtm

#164 Update README.md
  examples/create_rosa_cluster/create_rosa_sts_cluster/classic_sts/account_roles/README.md
Labels: approved, lgtm

#166 Update README.md
  examples/create_identity_provider/htpasswd/README.md
Labels: approved, lgtm

#167 Update README.md
  examples/create_identity_provider/google/README.md
Labels: approved, lgtm

#157 Update modify-cluster.md
  docs/modify-cluster.md
Labels: approved, lgtm

#162 Update README.md
  examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/cluster_with_managed_oidc_config/README.md
Labels: approved, lgtm

#165 Update README.md
  examples/create_identity_provider/ldap/README.md
Labels: approved, lgtm

#169 Update README.md
  examples/create_identity_provider/github/README.md
Labels: approved, lgtm

#168 Update README.md
  examples/create_identity_provider/gitlab/README.md
Labels: approved, lgtm
