Repository terraform-redhat/terraform-provider-rhcs, pull requests merged in 2024-01, with the labels that each got.

#475 github issue383: Fixing the description for
  docs/resources/cluster_rosa_classic.md
  provider/clusterrosaclassic/cluster_rosa_classic_resource.go
Labels: approved, lgtm

#470 Fix random string with symbols function
  tests/utils/helper/helper.go
Labels: approved, lgtm

#473 NO-ISSUE: Adding a note about updating magic import's attributes
  docs/guides/worker-machine-pool.md
  templates/guides/worker-machine-pool.md.tmpl
Labels: approved, jira/valid-reference, lgtm

#481 OCM-3021: MP taints can't be an empty array
  provider/machinepool/machine_pool_resource.go
  subsystem/machine_pool_resource_test.go
Labels: approved, jira/valid-reference, lgtm

#477 Add an option to prevent terraform.tfvars deletion
  tests/ci/profile_handler.go
  tests/e2e/negative_day_one_test.go
  tests/utils/exec/cluster.go
Labels: approved, lgtm

#467 Support RHCS_SOURCE and RHCS_VERSION for CI jobs
  tests/e2e/cluster_creation_test.go
  tests/e2e/e2e_suite_test.go
  tests/e2e/idps_test.go
  tests/e2e/machine_pool_test.go
  tests/e2e/verfication_post_day1_test.go
  tests/tf-manifests/rhcs/default-machine-pool/variable.tf
  tests/utils/constants/config.go
  tests/utils/constants/constants.go
  tests/utils/helper/manifests_handler.go
Labels: approved, lgtm

#462 OCM-5406 | fix: set att to empty if removed from plan
  provider/defaultingress/ingress.go
  subsystem/default_ingress_resource_test.go
Labels: approved, lgtm

#455 Add terraform-import machinepool test case
  tests/e2e/machine_pool_test.go
  tests/tf-manifests/rhcs/resource-import/main.tf
  tests/utils/exec/import.go
  tests/utils/exec/tf-exec.go
Labels: approved, lgtm, ok-to-test

#483 fix OCP-65981 :: change expected error syntax when no clusterID exists
  tests/e2e/idps_test.go
Labels: approved, lgtm

#476 automate ocp-64907 :: validate custom property operations on cluster
  tests/ci/profile_handler.go
  tests/e2e/general_day_two_test.go
  tests/tf-manifests/rhcs/clusters/rosa-classic/main.tf
  tests/tf-manifests/rhcs/clusters/rosa-classic/variables.tf
  tests/utils/constants/profile_defaults.go
  tests/utils/exec/cluster.go
  tests/utils/exec/tf-exec.go
  tests/utils/helper/helper.go
Labels: approved, lgtm

#486 OCM-5440: OCP-65645: Mp reconciliation feature TC
  tests/e2e/machine_pool_test.go
  tests/utils/cms/cms.go
Labels: approved, jira/valid-reference, lgtm

#490 add the option to destroy import idp resources
  tests/e2e/idps_test.go
Labels: approved, lgtm

#488 add qe_usage var env to track leakages
  tests/ci/profile_handler.go
  tests/utils/constants/config.go
  tests/utils/constants/profile_defaults.go
Labels: approved, lgtm

#494 OCM-5495: Remove depricated Dockerfile
  build/ci-tf-bin.Dockerfile
Labels: approved, jira/valid-reference, lgtm

#498 exclude OCP-65684 from CI until fixed
  tests/e2e/verfication_post_day1_test.go
Labels: approved, lgtm

#499 change the place of qe_usage property
  tests/utils/constants/config.go
  tests/utils/constants/constants.go
  tests/utils/constants/profile_defaults.go
Labels: approved, lgtm

#500 limit wait operators check to periodic jobs WAIT_OPERATORS var
  tests/e2e/cluster_creation_test.go
  tests/utils/constants/constants.go
Labels: approved, lgtm

#501 Fix OCP-65684 :: remove state file to prevent destructive import
  tests/e2e/verfication_post_day1_test.go
  tests/utils/constants/constants.go
  tests/utils/helper/manifests_handler.go
Labels: approved, lgtm

#505 fix typo in ingress error message
  provider/defaultingress/ingress.go
Labels: approved, lgtm, ok-to-test

#492 OCM-5496: OCP-63334 - Build a ROSA cluster with KMS key
  tests/ci/profile_handler.go
  tests/ci/profiles/tf_cluster_profile.yml
  tests/e2e/verfication_post_day1_test.go
  tests/tf-manifests/aws/kms/main.tf
  tests/tf-manifests/aws/kms/output.tf
  tests/tf-manifests/aws/kms/variables.tf
  tests/utils/cms/cms.go
  tests/utils/constants/constants.go
  tests/utils/exec/cluster.go
  tests/utils/exec/kms.go
Labels: approved, jira/valid-reference, lgtm

#504 automate idp reconciliation scenrios
  tests/e2e/idps_test.go
  tests/tf-manifests/rhcs/idps/ldap/output.tf
  tests/utils/cms/cms.go
Labels: approved, lgtm

#508 OCM-5422: Make the commit format more clear
  .github/pull_request_template.md
  .github/workflows/check-commit-format.yml
  CONTRIBUTE.md
Labels: approved, jira/valid-reference, lgtm

#495 OCM-5397 | chore: bump ocm-commons
  go.mod
  go.sum
  provider/clusterrosaclassic/cluster_rosa_classic_resource.go
  provider/clusterrosaclassic/upgrade/cluster_upgrade.go
  provider/oidcconfiginput/rosa_oidc_config_input_resource.go
  tests/e2e/verfication_post_day1_test.go
Labels: approved, lgtm

#511 OCM-2620 | build: Add files for building releases from Konflux
  .github/workflows/publish-release.yaml
  .goreleaser.yaml
  Dockerfile
  Makefile
  build/build_multiarch
Labels: approved, lgtm

#512 OCM-2620 | ci: Add pipelinerun file for Konflux
  .tekton/terraform-provider-rhcs-push.yaml
Labels: approved, lgtm

#515 OCM-5798 | chore: bump and use ocm-commons
  go.mod
  go.sum
  provider/clusterrosaclassic/cluster_rosa_classic_resource.go
  provider/common/helpers.go
  provider/oidcconfig/rosa_oidc_config_resource.go
Labels: approved, lgtm

#517 OCM-5833 | ci: update OCP-63334 test
  tests/e2e/verfication_post_day1_test.go
Labels: approved, lgtm

#518 OCM-4953 | fix: remove paths from SHA256SUM releases
  build/build_multiarch
Labels: approved, lgtm

#520 OCM-5833 | ci: update OCP-64904 OCP-68283 test
  tests/e2e/machine_pool_test.go
Labels: approved, lgtm
