Repository terraform-redhat/terraform-provider-rhcs, pull requests merged in 2024-02, with the labels that each got.

#521 OCM-5853: exclude commits validations for PRs created by specific authors
  .github/workflows/check-commit-format.yml
Labels: approved, jira/valid-reference, lgtm

#523 OCM-5853: Fix github user name: red-hat-konflux --> red-hat-konflux[bot]
  .github/workflows/check-commit-format.yml
Labels: approved, jira/valid-reference, lgtm

#507 OCM-5627 | ci: upgrade scenario test cases
  go.mod
  go.sum
  tests/ci/labels.go
  tests/ci/profile_handler.go
  tests/ci/profiles/tf_cluster_profile.yml
  tests/e2e/cluster_creation_test.go
  tests/e2e/cluster_upgrade_test.go
  tests/e2e/general_day_two_test.go
  tests/tf-manifests/rhcs/clusters/rosa-classic/main.tf
  tests/tf-manifests/rhcs/clusters/rosa-classic/variables.tf
  tests/utils/cms/cms.go
  tests/utils/constants/constants.go
  tests/utils/exec/cluster.go
  tests/utils/exec/tf-exec.go
  tests/utils/openshift/console.go
  tests/utils/openshift/openshift.go
Labels: approved, lgtm

#532 OCM-5980 | ci: fix teardown issue when the cluster failed
  tests/ci/profile_handler.go
Labels: approved, lgtm

#535 OCM-5853 | ci: Add "dependabot[bot]" to skip commit validations list
  .github/workflows/check-commit-format.yml
Labels: approved, lgtm

#510 OCM-5698 | ci: Implement proxy on rhcs rosa creation
  tests/ci/profile_handler.go
  tests/ci/profiles/tf_cluster_profile.yml
  tests/e2e/idps_test.go
  tests/tf-manifests/aws/proxy/main.tf
  tests/tf-manifests/aws/proxy/output.tf
  tests/tf-manifests/aws/proxy/variables.tf
  tests/tf-manifests/aws/security-groups/main.tf
  tests/tf-manifests/aws/security-groups/output.tf
  tests/tf-manifests/aws/vpc/main.tf
  tests/tf-manifests/rhcs/clusters/rosa-classic/variables.tf
  tests/utils/constants/constants.go
  tests/utils/constants/profile_defaults.go
  tests/utils/exec/proxy.go
Labels: approved, lgtm

#538 OCM-6007 | ci: validate proxy post cluster creation
  tests/e2e/verfication_post_day1_test.go
Labels: approved, lgtm

#540 OCM-5698 | ci: fix key-pair name duplication
  tests/tf-manifests/aws/proxy/main.tf
Labels: approved, lgtm

#539 OCM-5627 |ci: upgrade fix
  tests/ci/profile_handler.go
  tests/ci/profiles/tf_cluster_profile.yml
  tests/e2e/cluster_upgrade_test.go
  tests/utils/cms/versions.go
Labels: approved, lgtm

#537 OCM-5399 | fix: Remove duplicated wait function
  provider/clusterautoscaler/cluster_autoscaler_resource.go
  provider/clusterrosaclassic/cluster_rosa_classic_resource.go
  provider/clusterwaiter/cluster_waiter_resource.go
  provider/common/cluster_waiter.go
  provider/common/mock_clusterwait.go
  provider/defaultingress/ingress.go
  provider/groupmembership/group_membership_resource.go
  provider/kubeletconfig/kubeletconfig_resource.go
  provider/kubeletconfig/kubeletconfig_resource_test.go
  provider/machinepool/machine_pool_resource.go
  subsystem/cluster_resource_rosa_create_test.go
  subsystem/cluster_waiter_test.go
  subsystem/default_ingress_resource_test.go
  subsystem/group_membership_resource_test.go
  subsystem/machine_pool_resource_test.go
Labels: approved, lgtm

#509 OCM-5632 | feat: support password generate/hash in terraform provider
  .tekton/terraform-provider-rhcs-push.yaml
  docs/resources/cluster_rosa_classic.md
  examples/create_rosa_sts_cluster/classic_sts/cluster/output.tf
  go.sum
  provider/clusterrosaclassic/cluster_rosa_classic_datasource.go
  provider/clusterrosaclassic/cluster_rosa_classic_resource.go
  provider/clusterrosaclassic/cluster_rosa_classic_resource_test.go
  provider/clusterrosaclassic/cluster_rosa_classic_state.go
  provider/identityprovider/htpasswd.go
  provider/identityprovider/identity_provider_resource.go
  subsystem/cluster_resource_rosa_create_test.go
  subsystem/identity_provider_resource_test.go
  subsystem/main_test.go
Labels: approved, lgtm, ok-to-test

#544 OCM-6092 | fix: add "create_admin_user" in cluster datasource
  docs/data-sources/cluster_rosa_classic.md
  provider/clusterrosaclassic/cluster_rosa_classic_datasource.go
Labels: approved, lgtm

#542 OCM-4331 | ci: fix OCP-63141 to prevent CI failure
  tests/e2e/verfication_post_day1_test.go
Labels: approved, lgtm

#548 OCM-6113 | ci: Fix teardown KMS issue with kmsname and Upgrade sync issue
  tests/ci/profile_handler.go
  tests/e2e/cluster_upgrade_test.go
  tests/tf-manifests/aws/kms/variables.tf
Labels: approved, lgtm

#551 OCM-5551 | ci: Hide the sensitive information in terraform automation log
  tests/ci/profile_handler.go
  tests/e2e/verfication_post_day1_test.go
  tests/utils/exec/tf-exec.go
  tests/utils/log/constants.go
  tests/utils/log/logger.go
Labels: approved, lgtm

#552 OCM-6335 | ci: Update the OWNERS in rhcs automation
  tests/OWNERS
Labels: approved, lgtm

#553 OCM-6344 | feat: add a waiter for std compute nodes
  docs/resources/cluster_rosa_hcp.md
  provider/clusterrosa/classic/cluster_rosa_classic_resource.go
  provider/clusterrosa/hcp/datasource.go
  provider/clusterrosa/hcp/resource.go
  provider/clusterrosa/hcp/state.go
  provider/common/cluster_waiter.go
  provider/common/mock_clusterwait.go
  subsystem/hcp/cluster_resource_test.go
Labels: approved, lgtm

#554 OCM-5758 | fix: missing attributes from datasource of hcp mp
  docs/data-sources/hcp_machine_pool.md
  provider/machinepool/classic/machine_pool_datasource.go
  provider/machinepool/hcp/machine_pool_datasource.go
Labels: approved, lgtm

#557 Change example links to use tag v1.5.1
  docs/guides/machine-pool.md
  docs/guides/upgrading-cluster.md
  docs/index.md
  go.sum
  templates/guides/machine-pool.md.tmpl
  templates/guides/upgrading-cluster.md.tmpl
  templates/index.md.tmpl
Labels: approved, lgtm

#558 OCM-6074: Update Changelog with versions v1.5.0 and v1.5.1
  CHANGELOG.md
Labels: jira/valid-reference, lgtm

#561 OCM-5758 | fix: allow to patch subnet of hcp mp
  provider/machinepool/hcp/machine_pool_resource.go
  subsystem/hcp/machine_pool_resource_test.go
Labels: approved, lgtm

#556 OCM-5758 | fix: hcp-cluster and machine pool datasources
  docs/data-sources/cluster_rosa_hcp.md
  docs/data-sources/hcp_machine_pool.md
  provider/clusterrosa/hcp/datasource.go
  provider/machinepool/hcp/autoscaling.go
  provider/machinepool/hcp/aws_node_pool.go
  provider/machinepool/hcp/machine_pool_datasource.go
  provider/machinepool/hcp/machine_pool_resource.go
Labels: approved, lgtm
