Repository terraform-redhat/terraform-provider-rhcs, pull requests merged in 2024-05, with the labels that each got.

#644 OCM-7142 ci: Automate 72445/72449/72477/72486/72491/72496/72627/72468 (Day1 negative)
  tests/ci/profile_handler.go
  tests/e2e/cluster_autoscaler_day2_test.go
  tests/e2e/cluster_edit_test.go
  tests/e2e/cluster_misc_day2_test.go
  tests/e2e/hcp_ingress_test.go
  tests/e2e/hcp_machine_pool_test.go
  tests/e2e/negative_day_one_test.go
  tests/e2e/tuning_config.go
  tests/e2e/verfication_post_day1_test.go
  tests/tf-manifests/aws/proxy/main.tf
  tests/tf-manifests/aws/proxy/variables.tf
  tests/tf-manifests/aws/vpc/main.tf
  tests/tf-manifests/aws/vpc/variables.tf
  tests/tf-manifests/rhcs/clusters/rosa-hcp/main.tf
  tests/tf-manifests/rhcs/clusters/rosa-hcp/variables.tf
  tests/utils/constants/config.go
  tests/utils/constants/constants.go
  tests/utils/exec/cluster.go
  tests/utils/exec/proxy.go
  tests/utils/exec/vpc.go
  tests/utils/helper/assert.go
  tests/utils/helper/helper.go
Labels: approved, lgtm

#648 OCM-7820 | fix: etcd_kms_key_arn should not be editable
  provider/clusterrosa/hcp/resource.go
Labels: approved, lgtm

#651 OCM-7493 | chore: update konflux settings
  .tekton/terraform-provider-rhcs-push.yaml
Labels: approved, lgtm

#654 OCM-6805 | ci: Update 72452 (edit billing account)
  tests/e2e/cluster_edit_test.go
Labels: approved, lgtm

#657 OCM-7852 | fix: allow assumed-role into creator arn property
  provider/clusterrosa/common/consts.go
  provider/clusterrosa/common/consts_test.go
Labels: lgtm

#660 OCM-6718 | feat: Allow support of user defined tags on machinepools
  docs/resources/machine_pool.md
  go.mod
  go.sum
  provider/machinepool/classic/machine_pool_resource.go
  provider/machinepool/classic/machine_pool_state.go
  subsystem/machine_pool_resource_test.go
Labels: approved, lgtm, ok-to-test

#661 OCM-8044 | ci: Update classic profile openshift version
  tests/ci/profiles/tf_classic_cluster_profiles.yml
Labels: approved, lgtm

#663 OCM-8085 | fix: typo on message for oidc
  provider/oidcconfig/rosa_oidc_config_resource.go
  provider/oidcconfiginput/rosa_oidc_config_input_resource.go
Labels: approved, lgtm

#665 OCM-6806 | fix: fail faster on cloud region change
  provider/clusterrosa/classic/cluster_rosa_classic_resource.go
  provider/clusterrosa/hcp/resource.go
Labels: approved, lgtm

#666 OCM-8122 | ci: Setup cluster prefix/suffix config
  tests/utils/constants/config.go
  tests/utils/constants/constants.go
  tests/utils/helper/helper.go
Labels: approved, lgtm

#667 OCM-8137 | ci: Fix construct vpc tag args with empty region error
  tests/e2e/classic_machine_pool_test.go
Labels: approved, lgtm

#669 OCM-8263 | fix: adjust autoscaler docs to mention it is not currently available in hcp
  CONTRIBUTE.md
  docs/resources/hcp_cluster_autoscaler.md
  provider/autoscaler/hcp/resource.go
Labels: approved, lgtm

#670 OCM-8275 | ci: Fix teardown issue with VPC
  Makefile
  tests/ci/profile_handler.go
  tests/e2e/classic_machine_pool_test.go
  tests/e2e/hcp_machine_pool_test.go
  tests/e2e/negative_day_one_test.go
  tests/e2e/tuning_config.go
  tests/tf-manifests/aws/vpc/rosa-classic/main.tf
  tests/tf-manifests/aws/vpc/rosa-classic/output.tf
  tests/tf-manifests/aws/vpc/rosa-classic/variables.tf
  tests/tf-manifests/aws/vpc/rosa-hcp/main.tf
  tests/tf-manifests/aws/vpc/rosa-hcp/output.tf
  tests/tf-manifests/aws/vpc/rosa-hcp/variables.tf
  tests/tf-manifests/rhcs/clusters/rosa-hcp/main.tf
  tests/utils/constants/manifests.go
  tests/utils/exec/vpc.go
Labels: approved, lgtm

#671 OCM-8279 | ci: Fix M/L HCP cases
  tests/e2e/cluster_autoscaler_day2_test.go
  tests/e2e/cluster_edit_test.go
Labels: approved, lgtm

#668 OCM-6348 | ci: Setup upgrade y and z profiles
  tests/ci/profiles/tf_hcp_cluster_profiles.yml
  tests/e2e/classic_ingress_test.go
  tests/e2e/classic_machine_pool_test.go
  tests/e2e/cluster_autoscaler_day2_test.go
  tests/e2e/cluster_edit_test.go
  tests/e2e/cluster_upgrade_test.go
  tests/e2e/hcp_ingress_test.go
  tests/e2e/hcp_machine_pool_test.go
  tests/e2e/idps_test.go
  tests/e2e/negative_day_one_test.go
  tests/utils/cms/cms.go
  tests/utils/openshift/openshift.go
Labels: approved, lgtm

#672 OCM-8316 | ci: FIx HCP upgrade jobs
  tests/e2e/cluster_upgrade_test.go
Labels: approved, lgtm

#674 OCM-8334 | ci: Document RHCS_URL
  tests/README.md
Labels: approved, lgtm

#675 OCM-6718 | fix: include fetchUserTagsOnly param for classic machine pools
  provider/machinepool/classic/machine_pool_resource.go
Labels: approved, lgtm

#677 OCM-8378 | ci: Fix provider in TF manifests
  tests/tf-manifests/aws/account-roles/rosa-classic/main.tf
  tests/tf-manifests/aws/account-roles/rosa-hcp/main.tf
  tests/tf-manifests/aws/add-account-roles/rosa-classic/main.tf
  tests/tf-manifests/aws/add-account-roles/rosa-hcp/main.tf
  tests/tf-manifests/aws/oidc-provider-operator-roles/rosa-classic/main.tf
  tests/tf-manifests/aws/oidc-provider-operator-roles/rosa-hcp/main.tf
  tests/tf-manifests/rhcs/cluster-autoscaler/classic/main.tf
  tests/tf-manifests/rhcs/cluster-autoscaler/hcp/main.tf
  tests/tf-manifests/rhcs/clusters/rosa-classic/main.tf
  tests/tf-manifests/rhcs/clusters/rosa-hcp/main.tf
  tests/tf-manifests/rhcs/default-machine-pool/main.tf
  tests/tf-manifests/rhcs/dns/main.tf
  tests/tf-manifests/rhcs/idps/github/main.tf
  tests/tf-manifests/rhcs/idps/gitlab/main.tf
  tests/tf-manifests/rhcs/idps/google/main.tf
  tests/tf-manifests/rhcs/idps/htpasswd/main.tf
  tests/tf-manifests/rhcs/idps/ldap/main.tf
  tests/tf-manifests/rhcs/idps/multi-idp/main.tf
  tests/tf-manifests/rhcs/idps/openid/main.tf
  tests/tf-manifests/rhcs/ingresses/classic/main.tf
  tests/tf-manifests/rhcs/ingresses/hcp/main.tf
  tests/tf-manifests/rhcs/kubelet-config/main.tf
  tests/tf-manifests/rhcs/machine-pools/classic/main.tf
  tests/tf-manifests/rhcs/machine-pools/hcp/main.tf
  tests/tf-manifests/rhcs/resource-import/main.tf
  tests/tf-manifests/rhcs/rhcs-info/main.tf
  tests/tf-manifests/rhcs/tuning-config/main.tf
  tests/utils/constants/config.go
Labels: approved, lgtm

#679 OCM-8407 | ci: Update error message when idp url not set
  tests/e2e/idps_test.go
Labels: approved, lgtm
