Repository terraform-redhat/terraform-provider-rhcs, pull requests merged in 2024-08, with the labels that each got.

#733 OCM-10084 | ci: Fix ids:72514,75067 on HCP
  tests/e2e/classic_ingress_test.go
  tests/e2e/hcp_machine_pool_test.go
Labels: approved, lgtm

#734 OCM-8936 | ci: add support for imdsv2 for hcp cluster
  tests/ci/profiles/tf_hcp_cluster_profiles.yml
  tests/tf-manifests/rhcs/clusters/rosa-hcp/main.tf
  tests/tf-manifests/rhcs/clusters/rosa-hcp/variables.tf
  tests/tf-manifests/rhcs/machine-pools/hcp/main.tf
  tests/tf-manifests/rhcs/machine-pools/hcp/output.tf
  tests/tf-manifests/rhcs/machine-pools/hcp/variable.tf
  tests/utils/exec/machine-pools.go
Labels: approved, lgtm

#735 OCM-10096 | ci: Fix id:64757
  tests/ci/profiles/tf_classic_cluster_profiles.yml
  tests/ci/profiles/tf_hcp_cluster_profiles.yml
  tests/tf-manifests/rhcs/default-machine-pool/main.tf
  tests/tf-manifests/rhcs/default-machine-pool/output.tf
  tests/tf-manifests/rhcs/default-machine-pool/variable.tf
  tests/tf-manifests/rhcs/machine-pools/classic/main.tf
  tests/tf-manifests/rhcs/machine-pools/classic/output.tf
  tests/tf-manifests/rhcs/machine-pools/classic/variable.tf
Labels: approved, lgtm

#736 OCM-8937 | test: automated id:75392,75372,75373,75393,75414
  tests/ci/labels.go
  tests/e2e/cluster_edit_test.go
  tests/e2e/hcp_machine_pool_test.go
  tests/e2e/negative_day_one_test.go
  tests/e2e/verification_post_day1_test.go
  tests/utils/constants/constants.go
Labels: approved, lgtm

#737 OCM-10096 | ci: Fix default machine pool manifest
  tests/tf-manifests/rhcs/default-machine-pool/main.tf
Labels: approved, lgtm

#726 OCM-9046 | test: updated case id:63147
  tests/e2e/cluster_edit_test.go
  tests/utils/exec/cluster.go
Labels: approved, lgtm, ok-to-test

#717 OCM-8697 | test: update case ids:65961, 73154, 66408, 66410
  go.mod
  go.sum
  tests/ci/profile_handler.go
  tests/e2e/idps_test.go
  tests/e2e/negative_day_one_test.go
  tests/utils/helper/helper.go
Labels: approved, lgtm, ok-to-test

#740 OCM-10267 | fix: accept to reset component routes by removing parent field
  provider/defaultingress/classic/resource.go
  provider/defaultingress/component_routes.go
  subsystem/default_ingress_resource_test.go
Labels: approved, lgtm

#738 OCM-10267 | ci: Update id:73610,75067
  tests/e2e/classic_ingress_test.go
  tests/tf-manifests/rhcs/ingresses/classic/main.tf
  tests/tf-manifests/rhcs/ingresses/classic/variables.tf
  tests/utils/exec/ingress.go
Labels: approved, lgtm

#742 OCM-10343 | ci: Fix the sensitive leak of CA and billing account
  tests/README.md
  tests/utils/log/constants.go
Labels: approved, lgtm

#732 OCM-10019 | ci: update the OWNERS file
  tests/OWNERS
Labels: approved, lgtm

#746 OCM-10439 | fix: Set component_routes to empty object will cause provider bug
  provider/defaultingress/classic/resource.go
  tests/e2e/classic_ingress_test.go
Labels: approved, lgtm

#749 OCM-10200 | feat: Bump SDK + Add .idea to gitignore
  .gitignore
  go.mod
  go.sum
Labels: approved, lgtm

#752 OCM-10469 | ci: fix shared vpc creation failure on prow
  tests/ci/profile_handler.go
  tests/tf-manifests/aws/shared-vpc-policy-and-hosted-zone/main.tf
  tests/tf-manifests/aws/shared-vpc-policy-and-hosted-zone/variables.tf
  tests/tf-manifests/rhcs/clusters/rosa-classic/main.tf
  tests/tf-manifests/rhcs/clusters/rosa-classic/variables.tf
  tests/tf-manifests/rhcs/default-machine-pool/output.tf
  tests/tf-manifests/rhcs/default-machine-pool/variable.tf
  tests/tf-manifests/rhcs/ingresses/classic/variables.tf
  tests/tf-manifests/rhcs/machine-pools/classic/output.tf
  tests/tf-manifests/rhcs/machine-pools/classic/variable.tf
  tests/tf-manifests/rhcs/machine-pools/hcp/output.tf
  tests/tf-manifests/rhcs/machine-pools/hcp/variable.tf
  tests/utils/exec/cluster.go
  tests/utils/exec/shared-vpc-policy-and-hosted-zone.go
Labels: approved, lgtm

#753 OCM-10500 | chore: remove output from some unit tests
  provider/clusterrosa/classic/cluster_rosa_classic_resource_test.go
  provider/clusterrosa/common/consts_test.go
  provider/clusterrosa/hcp/resource_test.go
Labels: lgtm

#757 OCM-10542 | ci: Replace latest terramform version in image due to it has a bug
  build/ci-tf-e2e.Dockerfile
Labels: approved, lgtm

#760 OCM-10607 | ci: fix the cluster leak issue
  tests/ci/profile_handler.go
  tests/e2e/idps_test.go
  tests/e2e/verification_post_day1_test.go
  tests/utils/constants/config.go
  tests/utils/helper/helper.go
Labels: approved, lgtm

#761 OCM-10643 | ci: fix the ci failure of rosa-sts-ad medium+low cases
  tests/e2e/account_roles_test.go
  tests/e2e/classic_ingress_test.go
  tests/e2e/classic_machine_pool_test.go
Labels: approved, lgtm

#762 OCM-10642 | chore: bump terraform plugin framework
  go.mod
  go.sum
Labels: approved, lgtm

#756 OCM-10541 | ci: mask sensitive information in error
  tests/utils/exec/tf-exec.go
  tests/utils/log/logger.go
Labels: approved, lgtm

#766 OCM-10684 | ci: Fix tags issue when creating default MP
  provider/machinepool/classic/machine_pool_resource.go
Labels: approved, lgtm

#764 OCM-10640 | ci: Fix destroy resources if error in apply
  tests/e2e/negative_day_one_test.go
  tests/utils/exec/tf-exec.go
Labels: approved, lgtm

#771 OCM-10778 | ci: Reset rhcs CI using latest terraform version
  build/ci-tf-e2e.Dockerfile
  tests/ci/profile_handler.go
Labels: approved, lgtm

#769 OCM-10760 | chore: remove deprecated task
  .tekton/terraform-provider-rhcs-push.yaml
Labels: lgtm

#774 OCM-10817 | fix: check if tags are unknown prior to setting null
  provider/machinepool/classic/machine_pool_resource.go
  provider/machinepool/hcp/machine_pool_resource.go
  subsystem/classic/machine_pool_resource_test.go
  subsystem/hcp/machine_pool_resource_test.go
Labels: approved
