Repository terraform-redhat/terraform-provider-rhcs, pull requests merged in 2024-03, with the labels that each got.

#562 OCM-5758 | fix: [HCP] Correct rosa operator roles data source name
  docs/data-sources/rosa_hcp_operator_roles.md
  provider/rosa_operator_roles/hcp/rosa_operator_roles_data_source.go
Labels: approved, lgtm

#560 OCM-6438 | fix: add etcd kms key arn support to hcp clusters
  docs/data-sources/cluster_rosa_classic.md
  docs/data-sources/cluster_rosa_hcp.md
  docs/resources/cluster_rosa_classic.md
  docs/resources/cluster_rosa_hcp.md
  internal/ocm/resource/cluster.go
  internal/ocm/resource/cluster_test.go
  provider/clusterrosa/classic/cluster_rosa_classic_datasource.go
  provider/clusterrosa/classic/cluster_rosa_classic_resource.go
  provider/clusterrosa/hcp/datasource.go
  provider/clusterrosa/hcp/resource.go
  provider/clusterrosa/hcp/state.go
  provider/ocm_policies/hcp/ocm_policies_data_source.go
  provider/ocm_policies/hcp/ocm_policies_state.go
  provider/rosa_operator_roles/hcp/rosa_operator_roles_data_source.go
  provider/rosa_operator_roles/hcp/rosa_operator_roles_state.go
  subsystem/hcp/cluster_resource_test.go
  subsystem/hcp/hcp_test.go
  subsystem/hcp/machine_pool_resource_test.go
Labels: approved, lgtm

#575 OCM-6703 | ci: Hide possible sensitive message
  tests/e2e/verfication_post_day1_test.go
  tests/utils/log/constants.go
Labels: approved, lgtm

#576 OCM-6769 | fix: enforce some attributes for hcp
  docs/resources/cluster_rosa_hcp.md
  provider/clusterrosa/hcp/resource.go
  subsystem/hcp/cluster_resource_test.go
Labels: approved, lgtm

#578 OCM-6810 | fix: external id is computed only
  docs/resources/cluster_rosa_classic.md
  docs/resources/cluster_rosa_hcp.md
  provider/clusterrosa/classic/cluster_rosa_classic_resource.go
  provider/clusterrosa/hcp/resource.go
Labels: approved, lgtm

#569 OCM-6701 | test: [TF provider] Add Shared-VPC test profile
  .gitignore
  tests/ci/profile_handler.go
  tests/ci/profiles/tf_classic_cluster_profiles.yml
  tests/e2e/cluster_upgrade_test.go
  tests/e2e/general_day_two_test.go
  tests/e2e/machine_pool_test.go
  tests/tf-manifests/aws/account-roles/rosa-classic/main.tf
  tests/tf-manifests/aws/account-roles/rosa-classic/output.tf
  tests/tf-manifests/aws/account-roles/rosa-classic/variables.tf
  tests/tf-manifests/aws/add-account-roles/rosa-classic/output.tf
  tests/tf-manifests/aws/add-account-roles/rosa-classic/variables.tf
  tests/tf-manifests/aws/oidc-provider-operator-roles/rosa-classic/main.tf
  tests/tf-manifests/aws/oidc-provider-operator-roles/rosa-classic/output.tf
  tests/tf-manifests/aws/shared-vpc-policy-and-hosted-zone/main.tf
  tests/tf-manifests/aws/shared-vpc-policy-and-hosted-zone/output.tf
  tests/tf-manifests/aws/shared-vpc-policy-and-hosted-zone/variables.tf
  tests/tf-manifests/aws/vpc/main.tf
  tests/tf-manifests/aws/vpc/variables.tf
  tests/tf-manifests/rhcs/clusters/rosa-classic/main.tf
  tests/tf-manifests/rhcs/clusters/rosa-classic/variables.tf
  tests/utils/constants/constants.go
  tests/utils/constants/manifests.go
  tests/utils/exec/account-roles.go
  tests/utils/exec/cluster.go
  tests/utils/exec/dns-domain.go
  tests/utils/exec/oidc-provider-operator-roles.go
  tests/utils/exec/shared-vpc-policy-and-hosted-zone.go
  tests/utils/exec/vpc.go
Labels: approved, lgtm, ok-to-test

#581 Change channel group of STS classic cluster to stable.
  tests/ci/profiles/tf_classic_cluster_profiles.yml
Labels: approved, lgtm

#584 OCM-6889 | fix: Fix rhcs_rosa_oidc_config_input.private_key attribute to be sensitive
  docs/resources/rosa_oidc_config_input.md
  provider/oidcconfiginput/rosa_oidc_config_input_resource.go
Labels: approved, lgtm

#583 OCM-6387 | ci: Fix HCP cluster creation in CI
  tests/ci/profiles/tf_hcp_cluster_profiles.yml
  tests/tf-manifests/rhcs/clusters/rosa-hcp/main.tf
Labels: approved, lgtm

#585 OCM-6960 | ci: Fix failure of @OCP-63316
  tests/tf-manifests/aws/add-account-roles/rosa-classic/output.tf
Labels: approved, lgtm

#573 OCM-902: Verify imdsv2 value is set post cluster creation
  tests/ci/profile_handler.go
  tests/ci/profiles/tf_classic_cluster_profiles.yml
  tests/ci/profiles/tf_hcp_cluster_profiles.yml
  tests/e2e/verfication_post_day1_test.go
  tests/tf-manifests/rhcs/clusters/rosa-classic/main.tf
  tests/tf-manifests/rhcs/clusters/rosa-classic/variables.tf
  tests/utils/exec/cluster.go
Labels: approved, jira/valid-reference, lgtm, ok-to-test

#586 OCM-6992 | fix: docs for wait for std compute nodes
  docs/resources/cluster_rosa_hcp.md
  provider/clusterrosa/hcp/resource.go
Labels: approved, lgtm

#587 OCM-6387 | ci: Fix HCP jobs
  tests/tf-manifests/aws/oidc-provider-operator-roles/rosa-hcp/main.tf
Labels: approved, lgtm

#588 OCM-7006 | fix: require aws node pool field
  docs/resources/hcp_machine_pool.md
  provider/machinepool/hcp/machine_pool_resource.go
Labels: approved, lgtm

#589 OCM-7005 | fix: improve error message for autoscaling and replicas
  provider/machinepool/hcp/machine_pool_resource.go
Labels: approved, lgtm

#594 OCM-6347 | ci: Fix HCP testing
  tests/e2e/verfication_post_day1_test.go
Labels: approved, lgtm

#591 OCM-7020 | fix: tuning config id should be computed only
  docs/resources/tuning_config.md
  provider/tuningconfigs/resource.go
Labels: approved, lgtm

#592 OCM-7019 | fix: adjust docs to mention it requires jsonencode for tuning config
  docs/resources/tuning_config.md
  provider/tuningconfigs/resource.go
Labels: approved, lgtm

#593 OCM-7022 | fix: allow to supply version on create hcp mp
  provider/machinepool/hcp/machine_pool_resource.go
  subsystem/hcp/machine_pool_resource_test.go
Labels: approved, lgtm

#596 OCM-7042 | fix: hcp ingress id should be read only
  docs/resources/hcp_default_ingress.md
  provider/defaultingress/hcp/resource.go
  subsystem/hcp/default_ingress_resource_test.go
Labels: approved, lgtm

#595 OCM-6277 | feat: Support day 2 node pool for additional sceurity groups - bump OCM-SDK
  go.mod
  go.sum
Labels: approved, lgtm

#502 OCPQE-18948 | ci: Create cluster autoscaler with ocm terraform provider
  tests/ci/labels.go
  tests/e2e/cluster_autoscaler_day2_test.go
  tests/tf-manifests/rhcs/cluster-autoscaler/main.tf
  tests/tf-manifests/rhcs/cluster-autoscaler/output.tf
  tests/tf-manifests/rhcs/cluster-autoscaler/variable.tf
  tests/utils/cms/cms.go
  tests/utils/constants/manifests.go
  tests/utils/exec/cluster-autoscaler.go
Labels: approved, lgtm, ok-to-test
