Repository terraform-redhat/terraform-provider-rhcs, pull requests merged in 2024-09, with the labels that each got.

#773 OCM-10609 | ci: Tuning Configs support yaml
  tests/e2e/hcp_machine_pool_test.go
  tests/e2e/tuning_config_test.go
  tests/tf-manifests/rhcs/tuning-config/main.tf
  tests/tf-manifests/rhcs/tuning-config/variable.tf
  tests/utils/exec/tuning-configs.go
  tests/utils/helper/file.go
  tests/utils/helper/tuningconfig.go
Labels: approved, lgtm

#730 OCM-9270 | ci: include default account role prefix for classic cluster
  tests/tf-manifests/aws/account-roles/rosa-classic/main.tf
  tests/tf-manifests/aws/add-account-roles/rosa-classic/main.tf
Labels: approved, lgtm

#777 OCM-10817 | ci: Update id:72510
  tests/e2e/hcp_machine_pool_test.go
  tests/tf-manifests/rhcs/machine-pools/hcp/output.tf
  tests/utils/exec/machine-pools.go
Labels: approved, lgtm

#770 OCM-8194 | ci: Setup TF account/operator roles modules in tests manifests
  tests/ci/profile_handler.go
  tests/e2e/account_roles_test.go
  tests/tf-manifests/aws/account-roles/rosa-classic/main.tf
  tests/tf-manifests/aws/account-roles/rosa-classic/output.tf
  tests/tf-manifests/aws/account-roles/rosa-classic/variables.tf
  tests/tf-manifests/aws/account-roles/rosa-hcp/main.tf
  tests/tf-manifests/aws/account-roles/rosa-hcp/output.tf
  tests/tf-manifests/aws/account-roles/rosa-hcp/variables.tf
  tests/tf-manifests/aws/add-account-roles/rosa-classic/main.tf
  tests/tf-manifests/aws/add-account-roles/rosa-classic/output.tf
  tests/tf-manifests/aws/add-account-roles/rosa-classic/variables.tf
  tests/tf-manifests/aws/add-account-roles/rosa-hcp/main.tf
  tests/tf-manifests/aws/add-account-roles/rosa-hcp/output.tf
  tests/tf-manifests/aws/add-account-roles/rosa-hcp/variables.tf
  tests/tf-manifests/aws/oidc-provider-operator-roles/rosa-classic/main.tf
  tests/tf-manifests/aws/oidc-provider-operator-roles/rosa-classic/output.tf
  tests/tf-manifests/aws/oidc-provider-operator-roles/rosa-classic/variables.tf
  tests/tf-manifests/aws/oidc-provider-operator-roles/rosa-hcp/main.tf
  tests/tf-manifests/aws/oidc-provider-operator-roles/rosa-hcp/output.tf
  tests/tf-manifests/aws/oidc-provider-operator-roles/rosa-hcp/variables.tf
  tests/utils/exec/account-roles.go
  tests/utils/exec/oidc-provider-operator-roles.go
Labels: approved, lgtm

#778 OCM-10873 | ci: Use shared vpc module in tests
  tests/ci/profile_handler.go
  tests/tf-manifests/aws/shared-vpc-policy-and-hosted-zone/main.tf
  tests/tf-manifests/aws/shared-vpc-policy-and-hosted-zone/output.tf
  tests/utils/exec/shared-vpc-policy-and-hosted-zone.go
Labels: approved, lgtm

#780 OCM-5019 | fix: validates negative durations
  provider/autoscaler/classic/resource.go
  provider/autoscaler/hcp/resource.go
  provider/autoscaler/validators.go
  subsystem/classic/cluster_autoscaler_resource_test.go
Labels: lgtm

#779 OCM-10872 | ci: Use RHCS VPC module in tests
  go.mod
  go.sum
  tests/ci/profile_handler.go
  tests/e2e/account_roles_test.go
  tests/e2e/classic_machine_pool_test.go
  tests/e2e/hcp_machine_pool_test.go
  tests/e2e/negative_day_one_test.go
  tests/e2e/tuning_config_test.go
  tests/tf-manifests/aws/vpc/rosa-classic/main.tf
  tests/tf-manifests/aws/vpc/rosa-classic/output.tf
  tests/tf-manifests/aws/vpc/rosa-classic/variables.tf
  tests/tf-manifests/aws/vpc/rosa-hcp/main.tf
  tests/tf-manifests/aws/vpc/rosa-hcp/output.tf
  tests/tf-manifests/aws/vpc/rosa-hcp/variables.tf
  tests/utils/exec/vpc.go
Labels: approved, lgtm

#783 OCM-11003 | chore: Aligned QE Approvers with those of ROSA CLI project
  OWNERS
Labels: approved, lgtm

#782 OCM-10961 | fix: warning message is referring to classic on HCP clusters
  CONTRIBUTE.md
  provider/defaultingress/hcp/resource.go
  provider/machinepool/hcp/machine_pool_resource.go
  tests/tf-manifests/aws/shared-vpc-policy-and-hosted-zone/main.tf
Labels: approved, lgtm, ok-to-test

#785 OCM-10738 | feat: add sensitive to passwords/secret attributes
  examples/create_identity_provider/github/variables.tf
  examples/create_identity_provider/gitlab/variables.tf
  examples/create_identity_provider/google/variables.tf
  examples/create_identity_provider/openid/variables.tf
  tests/tf-manifests/rhcs/idps/github/variables.tf
  tests/tf-manifests/rhcs/idps/gitlab/variables.tf
  tests/tf-manifests/rhcs/idps/google/variables.tf
  tests/tf-manifests/rhcs/idps/multi-idp/variables.tf
  tests/tf-manifests/rhcs/idps/openid/variables.tf
Labels: lgtm

#784 OCM-10997 | ci: Fix id 65380,72510
  tests/e2e/account_roles_test.go
Labels: approved, lgtm

#788 OCM-10738 | feat: Add more sensitive to pwds/secrets manifests attrib…
  examples/create_identity_provider/htpasswd/variables.tf
  tests/tf-manifests/rhcs/clusters/rosa-classic/variables.tf
  tests/tf-manifests/rhcs/idps/htpasswd/variables.tf
  tests/tf-manifests/rhcs/idps/ldap/variables.tf
Labels: approved, lgtm

#789 OCM-10612 | feat: adjust docs for upgrading Classic/HCP clusters
  docs/guides/upgrading-classic-cluster.md
  docs/guides/upgrading-hcp-cluster.md
  templates/guides/upgrading-classic-cluster.md.tmpl
  templates/guides/upgrading-hcp-cluster.md.tmpl
Labels: approved, lgtm

#781 OCM-10873 | ci: Fix Shared VPC
  examples/create_identity_provider/htpasswd/variables.tf
  tests/ci/profile_handler.go
  tests/tf-manifests/aws/shared-vpc-policy-and-hosted-zone/main.tf
  tests/tf-manifests/aws/shared-vpc-policy-and-hosted-zone/output.tf
  tests/tf-manifests/aws/vpc/rosa-hcp/variables.tf
  tests/tf-manifests/rhcs/clusters/rosa-classic/variables.tf
  tests/tf-manifests/rhcs/idps/htpasswd/variables.tf
  tests/tf-manifests/rhcs/idps/ldap/variables.tf
  tests/utils/exec/shared-vpc-policy-and-hosted-zone.go
Labels: approved, lgtm

#791 OCM-11186 | fix: adjust user role RE
  provider/clusterrosa/common/consts.go
  provider/clusterrosa/common/consts_test.go
Labels: approved, lgtm

#792 OCM-5019 | ci: Updated/Created ids 76199,72526
  provider/autoscaler/classic/resource.go
  tests/e2e/cluster_autoscaler_day2_test.go
Labels: approved, lgtm

#795 OCM-10344 | chore: update changes for 1.6.4
  CHANGELOG.md
Labels: approved, lgtm

#797 OCM-11280 | ci: Fix tests panicking in BeforeEach
  tests/e2e/account_roles_test.go
  tests/e2e/dns_test.go
  tests/e2e/hcp_ingress_test.go
  tests/e2e/verification_post_day1_test.go
Labels: approved, lgtm

#790 OCM-7317 | feat: add support for registry config
  .gitignore
  Makefile
  docs/data-sources/cluster_rosa_hcp.md
  docs/resources/cluster_rosa_hcp.md
  go.mod
  go.sum
  provider/clusterrosa/hcp/datasource.go
  provider/clusterrosa/hcp/resource.go
  provider/clusterrosa/hcp/state.go
  provider/common/planmodifiers/main_test.go
  provider/common/planmodifiers/redacted_modifier.go
  provider/common/planmodifiers/redacted_modifier_test.go
  provider/registry_config/helpers.go
  provider/registry_config/main_test.go
  provider/registry_config/resource.go
  provider/registry_config/state.go
  provider/registry_config/state_test.go
  subsystem/hcp/cluster_resource_test.go
Labels: approved, lgtm

#793 OCM-9892 | feat: add root disk size to TF provider
  docs/data-sources/cluster_rosa_hcp.md
  docs/data-sources/hcp_machine_pool.md
  docs/resources/cluster_rosa_hcp.md
  docs/resources/hcp_machine_pool.md
  provider/clusterrosa/hcp/datasource.go
  provider/clusterrosa/hcp/resource.go
  provider/clusterrosa/hcp/state.go
  provider/machinepool/classic/machine_pool_resource.go
  provider/machinepool/hcp/aws_node_pool.go
  provider/machinepool/hcp/machine_pool_resource.go
  subsystem/hcp/cluster_resource_test.go
  subsystem/hcp/machine_pool_resource_test.go
Labels: approved, lgtm, ok-to-test
