Repository terraform-redhat/terraform-provider-rhcs, pull requests merged in 2024-10, with the labels that each got.

#806 OCM-11554 | fix: empty list as default value for registry config
  provider/common/attrvalidators/conflicts_with_not_empty.go
  provider/common/attrvalidators/conflicts_with_not_empty_test.go
  provider/common/attrvalidators/main_test.go
  provider/common/planmodifiers/redacted_modifier_test.go
  provider/registry_config/resource.go
  subsystem/hcp/cluster_resource_test.go
Labels: approved, lgtm

#804 OCM-11524 | ci: Fix id:63152
  tests/e2e/cluster_upgrade_test.go
Labels: approved, lgtm

#807 OCM-11554 | fix for allowedRegistriesForImport
  provider/registry_config/helpers.go
Labels: approved, lgtm

#808 OCM-11614 | test: Update the ami name for proxy launching due to the …
  tests/tf-manifests/aws/proxy/main.tf
Labels: approved, lgtm

#805 OCM-10805 | ci: Automate ids:76499,76500,76501
  tests/ci/labels.go
  tests/ci/profiles/tf_hcp_cluster_profiles.yml
  tests/e2e/cluster_edit_test.go
  tests/e2e/verification_post_day1_test.go
  tests/tf-manifests/rhcs/clusters/rosa-hcp/main.tf
  tests/tf-manifests/rhcs/clusters/rosa-hcp/variables.tf
  tests/utils/cms/cms.go
  tests/utils/cms/endpoints.go
  tests/utils/exec/cluster.go
  tests/utils/helper/certificate.go
  tests/utils/helper/registry.go
  tests/utils/profilehandler/file.go
  tests/utils/profilehandler/handler.go
  tests/utils/profilehandler/profile.go
Labels: approved, lgtm

#803 OCM-9891 | test: Automated ids:69143,69144,76344,76345
  go.mod
  go.sum
  tests/e2e/classic_machine_pool_test.go
  tests/e2e/machine_pool_test.go
  tests/e2e/negative_day_one_test.go
  tests/e2e/verification_post_day1_test.go
  tests/tf-manifests/rhcs/clusters/rosa-hcp/main.tf
  tests/tf-manifests/rhcs/clusters/rosa-hcp/output.tf
  tests/tf-manifests/rhcs/clusters/rosa-hcp/variables.tf
  tests/tf-manifests/rhcs/machine-pools/rosa-hcp/main.tf
  tests/tf-manifests/rhcs/machine-pools/rosa-hcp/output.tf
  tests/tf-manifests/rhcs/machine-pools/rosa-hcp/variable.tf
  tests/utils/constants/constants.go
Labels: approved, lgtm, ok-to-test

#814 OCM-11748 | ci: Fix ids 65380,76501,70128
  tests/e2e/account_roles_test.go
  tests/e2e/cluster_edit_test.go
  tests/e2e/kubelet_config_test.go
Labels: approved, lgtm

#811 OCM-9890 | ci: include worker_disk_size for profile rosa-hcp-ad
  tests/ci/profiles/tf_hcp_cluster_profiles.yml
Labels: approved, lgtm, ok-to-test

#819 OCM-11660 | chore: bump changelogs to 1.6.5
  CHANGELOG.md
Labels: approved, lgtm

#812 OCM-11739 | fix: add lock to guarantee only one kubelet config for classic cluster
  provider/common/mutex.go
  provider/kubeletconfig/kubeletconfig_resource.go
Labels: approved, lgtm

#820 OCM-11805 | ci: Review version and version pattern usage
  tests/ci/profiles/tf_classic_cluster_profiles.yml
  tests/ci/profiles/tf_hcp_cluster_profiles.yml
  tests/e2e/account_roles_test.go
  tests/e2e/cluster_upgrade_test.go
  tests/e2e/e2e_suite_test.go
  tests/utils/constants/constants.go
  tests/utils/constants/version.go
  tests/utils/profilehandler/file.go
  tests/utils/profilehandler/handler.go
  tests/utils/profilehandler/profile.go
Labels: approved, lgtm

#821 OCM-11840 | ci: Centralize environment variables
  tests/e2e/account_roles_test.go
  tests/e2e/cluster_creation_test.go
  tests/e2e/cluster_destroy_test.go
  tests/e2e/cluster_misc_day2_test.go
  tests/e2e/cluster_upgrade_test.go
  tests/e2e/e2e_suite_test.go
  tests/e2e/hcp_machine_pool_test.go
  tests/e2e/idps_test.go
  tests/e2e/verification_post_day1_test.go
  tests/utils/cms/connection.go
  tests/utils/config/config.go
  tests/utils/constants/config.go
  tests/utils/constants/constants.go
  tests/utils/exec/manifests/manifests.go
  tests/utils/helper/helper.go
  tests/utils/helper/manifests_handler.go
  tests/utils/openshift/console.go
  tests/utils/openshift/openshift.go
  tests/utils/profilehandler/file.go
  tests/utils/profilehandler/handler.go
  tests/utils/profilehandler/profile_defaults.go
Labels: approved, lgtm

#824 fix: updated to allow iam role for creator arn
  provider/clusterrosa/common/consts.go
Labels: needs-ok-to-test

#817 OCM-11521 | fix: validate custom machinepool disk size
  go.mod
  go.sum
  internal/ocm/resource/cluster.go
  internal/ocm/resource/cluster_test.go
  provider/clusterrosa/classic/cluster_rosa_classic_resource.go
  provider/clusterrosa/hcp/resource.go
  provider/machinepool/classic/machine_pool_resource.go
  provider/machinepool/hcp/machine_pool_resource.go
  subsystem/classic/cluster_resource_rosa_create_test.go
  subsystem/classic/machine_pool_resource_test.go
  subsystem/hcp/cluster_resource_test.go
  subsystem/hcp/machine_pool_resource_test.go
Labels: ok-to-test

#835 OCM-12146 | chore: bump changelogs to v1.6.6
  CHANGELOG.md
Labels: lgtm
